#!/usr/bin/env python3
"""Generate parametric-differentiation q036-q053 TypeScript batch."""
import json
import math
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from question_ts import write_questions_ts

BASE = {
    "level": "A-Level Maths",
    "topic": "Year 2 Pure",
    "subtopic": "Parametric differentiation",
    "subtopicId": "al.y2.pure.parametric-differentiation",
    "questionDiagram": None,
}

def step(n, desc, work, expl):
    return {
        "stepNumber": n,
        "description": desc,
        "workingLatex": work,
        "explanation": expl,
        "diagram": None,
    }

def make_q(qid, difficulty, marks, answer_type, tags, question_text, steps, final_answer):
    return {
        **BASE,
        "id": f"al.y2.pure.parametric-differentiation.{qid}",
        "difficulty": difficulty,
        "marks": marks,
        "answerType": answer_type,
        "tags": tags,
        "questionText": question_text,
        "workedSolution": {"steps": steps, "finalAnswer": final_answer},
    }

questions = []

# ── q036 Intermediate: dy/dx in terms of t ──────────────────────────────────
questions.append(make_q(
    "q036", "Intermediate", 4, "expression",
    ["parametric differentiation", "first derivative", "quotient rule"],
    r"A curve $C$ has parametric equations $x = t^{2}$ and $y = t^{3} + 1$, where $t \neq 0$. Find $\dfrac{dy}{dx}$ in terms of $t$.",
    [
        step(1, "Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = 2t",
             "The first step in parametric differentiation is to find how each coordinate changes as the parameter $t$ changes. For $x = t^{2}$, the power rule gives $2t$."),
        step(2, "Differentiate $y$ with respect to $t$",
             r"\frac{dy}{dt} = 3t^{2}",
             "Applying the power rule to $y = t^{3} + 1$ gives $3t^{2}$. The constant $1$ differentiates to zero."),
        step(3, "Recall the parametric chain rule for $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{dy/dt}{dx/dt}",
             "Because both $x$ and $y$ are defined through the same parameter $t$, the gradient with respect to $x$ is found by dividing the rate of change of $y$ by the rate of change of $x$."),
        step(4, "Substitute the derivatives",
             r"\frac{dy}{dx} = \frac{3t^{2}}{2t}",
             "Placing $3t^{2}$ over $2t$ combines the two rates of change into a single expression for the gradient."),
        step(5, "Cancel the common factor of $t$",
             r"\frac{dy}{dx} = \frac{3t}{2}",
             "Since $t \neq 0$, we can cancel one factor of $t$ from numerator and denominator. The result is a simple linear expression in $t$."),
        step(6, "Note the domain restriction",
             r"t \neq 0 \Rightarrow \frac{dx}{dt} \neq 0",
             "The formula is valid only where $dx/dt \neq 0$, which here means $t \neq 0$. At $t = 0$ the curve has a vertical tangent."),
        step(7, "Check at $t = 2$",
             r"\left.\frac{dy}{dx}\right|_{t=2} = \frac{3(2)}{2} = 3",
             "Substituting $t = 2$ gives a gradient of $3$, which is a reasonable check on the algebra."),
        step(8, "Interpret the sign of the gradient",
             r"t > 0 \Rightarrow \frac{dy}{dx} > 0;\quad t < 0 \Rightarrow \frac{dy}{dx} < 0",
             "The gradient has the same sign as $t$: the curve rises with $x$ for positive $t$ and falls for negative $t$."),
        step(9, "State the final answer",
             r"\frac{dy}{dx} = \frac{3t}{2}",
             "The gradient of the curve at a general parameter value $t$ is $3t/2$."),
    ],
    r"$\dfrac{dy}{dx} = \dfrac{3t}{2}$.",
))

# ── q037 Intermediate: evaluate dy/dx at a point ────────────────────────────
questions.append(make_q(
    "q037", "Intermediate", 4, "value",
    ["parametric differentiation", "first derivative", "evaluation"],
    r"A curve has parametric equations $x = 3t + 1$ and $y = t^{2}$. Find the value of $\dfrac{dy}{dx}$ at the point where $t = 2$.",
    [
        step(1, "Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = 3",
             "The $x$-equation is linear in $t$, so its derivative is the constant $3$."),
        step(2, "Differentiate $y$ with respect to $t$",
             r"\frac{dy}{dt} = 2t",
             "Differentiating $t^{2}$ with respect to $t$ gives $2t$ by the power rule."),
        step(3, "Write the parametric formula for $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{dy/dt}{dx/dt}",
             "The gradient with respect to $x$ is the ratio of the two parametric derivatives."),
        step(4, "Substitute the derivatives",
             r"\frac{dy}{dx} = \frac{2t}{3}",
             "Dividing $2t$ by $3$ gives the gradient as a function of $t$."),
        step(5, "Substitute $t = 2$",
             r"\left.\frac{dy}{dx}\right|_{t=2} = \frac{2(2)}{3}",
             "The question asks for the gradient at the specific parameter value $t = 2$, so we evaluate the expression there."),
        step(6, "Evaluate the fraction",
             r"\frac{dy}{dx} = \frac{4}{3}",
             "Multiplying gives $4/3$, which is the exact gradient at that point on the curve."),
        step(7, "Find the coordinates at $t = 2$",
             r"x = 7,\quad y = 4 \Rightarrow (7,\, 4)",
             "Finding the point confirms we are evaluating at a valid location: $x = 3(2)+1 = 7$ and $y = 2^{2} = 4$."),
        step(8, "Interpret the gradient",
             r"\frac{4}{3} > 0",
             "A positive gradient means the tangent line at $(7, 4)$ slopes upward as $x$ increases."),
        step(9, "State the final answer",
             r"\frac{dy}{dx} = \frac{4}{3}",
             "The gradient of the curve at $t = 2$ is $4/3$."),
    ],
    r"$\dfrac{dy}{dx} = \dfrac{4}{3}$ at $t = 2$.",
))

# ── q038 Intermediate: second derivative (constant) ─────────────────────────
questions.append(make_q(
    "q038", "Intermediate", 5, "value",
    ["parametric differentiation", "second derivative"],
    r"A curve is defined by $x = t$ and $y = t^{2} + t$. Find $\dfrac{d^{2}y}{dx^{2}}$.",
    [
        step(1, "Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = 1",
             "Since $x = t$, the rate of change of $x$ with respect to $t$ is simply $1$."),
        step(2, "Differentiate $y$ with respect to $t$",
             r"\frac{dy}{dt} = 2t + 1",
             "Differentiating $t^{2} + t$ term by term gives $2t + 1$."),
        step(3, "Find the first derivative $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{2t + 1}{1} = 2t + 1",
             "Dividing $dy/dt$ by $dx/dt$ gives the gradient as a function of $t$. Here it simplifies to a linear expression."),
        step(4, "Recall the second-derivative formula",
             r"\frac{d^{2}y}{dx^{2}} = \frac{\dfrac{d}{dt}\!\left(\dfrac{dy}{dx}\right)}{\dfrac{dx}{dt}}",
             "To differentiate the gradient with respect to $x$, we first differentiate $\dfrac{dy}{dx}$ with respect to $t$, then divide by $dx/dt$. This is the parametric version of the second derivative."),
        step(5, "Differentiate $\dfrac{dy}{dx}$ with respect to $t$",
             r"\frac{d}{dt}(2t + 1) = 2",
             "Since $\dfrac{dy}{dx} = 2t + 1$, differentiating with respect to $t$ gives the constant $2$."),
        step(6, "Divide by $\dfrac{dx}{dt}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{2}{1} = 2",
             "Dividing by $dx/dt = 1$ leaves the second derivative unchanged."),
        step(7, "Connect to Cartesian form",
             r"y = x^{2} + x \Rightarrow \frac{dy}{dx} = 2x + 1,\quad \frac{d^{2}y}{dx^{2}} = 2",
             "Eliminating $t$ gives $y = x^{2} + x$, a parabola opening upward. Its second derivative is indeed the constant $2$."),
        step(8, "Interpret the result",
             r"\frac{d^{2}y}{dx^{2}} = 2 > 0",
             "A positive constant second derivative means the curve is concave up everywhere: it bends upward like a parabola."),
        step(9, "State the final answer",
             r"\frac{d^{2}y}{dx^{2}} = 2",
             "The second derivative with respect to $x$ is $2$ at every point on the curve."),
    ],
    r"$\dfrac{d^{2}y}{dx^{2}} = 2$.",
))

# ── q039 Intermediate: stationary points ────────────────────────────────────
questions.append(make_q(
    "q039", "Intermediate", 6, "coordinates",
    ["parametric differentiation", "stationary points", "first derivative"],
    r"A curve $C$ has parametric equations $x = t^{2}$ and $y = t^{3} - 3t$, where $t \neq 0$. Find the coordinates of the stationary points on $C$.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             r"\frac{dx}{dt} = 2t,\qquad \frac{dy}{dt} = 3t^{2} - 3",
             "Both parametric derivatives are needed before we can form $\dfrac{dy}{dx}$."),
        step(2, "Write $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{3t^{2} - 3}{2t}",
             "The gradient with respect to $x$ is the ratio of the two parametric derivatives."),
        step(3, "State the stationary-point condition",
             r"\frac{dy}{dx} = 0",
             "A stationary point occurs where the tangent is horizontal, so the gradient with respect to $x$ must be zero."),
        step(4, "Set the numerator of $\dfrac{dy}{dx}$ equal to zero",
             r"3t^{2} - 3 = 0",
             "Since $t \neq 0$, the denominator $2t$ is non-zero, so we only need the numerator to vanish."),
        step(5, "Solve for $t$",
             r"3t^{2} = 3 \Rightarrow t^{2} = 1 \Rightarrow t = \pm 1",
             "Dividing by $3$ and taking square roots gives two parameter values. Both satisfy $t \neq 0$."),
        step(6, "Find coordinates when $t = 1$",
             r"x = 1^{2} = 1,\quad y = 1 - 3 = -2 \Rightarrow (1,\, -2)",
             "Substituting $t = 1$ into both parametric equations gives the first stationary point."),
        step(7, "Find coordinates when $t = -1$",
             r"x = (-1)^{2} = 1,\quad y = -1 + 3 = 2 \Rightarrow (1,\, 2)",
             "Substituting $t = -1$ gives the second stationary point. Notice both have $x = 1$."),
        step(8, "Verify $dx/dt \neq 0$ at both values",
             r"t = \pm 1 \Rightarrow \frac{dx}{dt} = \pm 2 \neq 0",
             "At both parameter values the $x$-coordinate is changing, so the stationary-point condition is valid."),
        step(9, "Interpret the geometry",
             r"\text{Both points share } x = 1 \text{ but have different } y\text{-values}",
             "The curve loops or folds so that two different parameter values map to the same $x$-coordinate but different heights."),
        step(10, "State the final answer",
             r"(1,\, -2) \text{ and } (1,\, 2)",
             "The stationary points are $(1, -2)$ and $(1, 2)$."),
    ],
    r"The stationary points are $(1,\, -2)$ and $(1,\, 2)$.",
))

# ── q040 Intermediate: equation of normal ───────────────────────────────────
questions.append(make_q(
    "q040", "Intermediate", 5, "equation",
    ["parametric differentiation", "normal", "straight line"],
    r"A curve has parametric equations $x = t$ and $y = t^{2}$. Find the equation of the normal to the curve at the point where $t = 1$, giving your answer in the form $ax + by + c = 0$ where $a$, $b$ and $c$ are integers.",
    [
        step(1, "Find the coordinates at $t = 1$",
             r"x = 1,\quad y = 1 \Rightarrow (1,\, 1)",
             "Substituting $t = 1$ into both equations locates the point on the curve."),
        step(2, "Differentiate parametrically",
             r"\frac{dx}{dt} = 1,\qquad \frac{dy}{dt} = 2t",
             "We need the gradient of the tangent before we can find the normal."),
        step(3, "Find $\dfrac{dy}{dx}$ at $t = 1$",
             r"\frac{dy}{dx} = \frac{2t}{1} = 2t \Rightarrow \left.\frac{dy}{dx}\right|_{t=1} = 2",
             "At $t = 1$ the tangent gradient is $2$, meaning the tangent rises $2$ units for every $1$ unit across."),
        step(4, "Find the gradient of the normal",
             r"m_{\text{normal}} = -\frac{1}{2}",
             "The normal is perpendicular to the tangent, so its gradient is the negative reciprocal of $2$."),
        step(5, "Write the point-gradient form",
             r"y - 1 = -\frac{1}{2}(x - 1)",
             "Using point $(1, 1)$ and gradient $-1/2$ gives the equation of the normal line."),
        step(6, "Expand the right-hand side",
             r"y - 1 = -\frac{x}{2} + \frac{1}{2}",
             "Distributing $-1/2$ across $(x - 1)$ prepares the equation for rearrangement."),
        step(7, "Rearrange into the required form",
             r"y = -\frac{x}{2} + \frac{3}{2}",
             "Adding $1$ to $1/2$ gives $3/2$ on the right-hand side."),
        step(8, "Clear fractions and rearrange",
             r"2y = -x + 3 \Rightarrow x + 2y - 3 = 0",
             "Multiplying through by $2$ and collecting terms on one side gives integer coefficients."),
        step(9, "Verify the normal passes through $(1, 1)$",
             r"1 + 2(1) - 3 = 0 \quad \checkmark",
             "Substituting the point confirms the equation is correct."),
        step(10, "State the final answer",
             r"x + 2y - 3 = 0",
             "The normal at $(1, 1)$ has equation $x + 2y - 3 = 0$."),
    ],
    r"The normal has equation $x + 2y - 3 = 0$.",
))

# ── q041 Intermediate: find parameter for given gradient ──────────────────
questions.append(make_q(
    "q041", "Intermediate", 5, "value",
    ["parametric differentiation", "find parameter", "gradient"],
    r"A curve has parametric equations $x = 2t$ and $y = t^{3}$. Find the values of $t$ for which the gradient of the curve is $4$.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             r"\frac{dx}{dt} = 2,\qquad \frac{dy}{dt} = 3t^{2}",
             "Both parametric derivatives are required to form the gradient."),
        step(2, "Write $\dfrac{dy}{dx}$ in terms of $t$",
             r"\frac{dy}{dx} = \frac{3t^{2}}{2}",
             "Dividing $dy/dt$ by $dx/dt$ gives the gradient as a function of $t$."),
        step(3, "Set the gradient equal to $4$",
             r"\frac{3t^{2}}{2} = 4",
             "The question specifies that the gradient equals $4$, so we equate the expression to $4$."),
        step(4, "Multiply both sides by $2$",
             r"3t^{2} = 8",
             "Clearing the denominator isolates the $t^{2}$ term."),
        step(5, "Divide by $3$",
             r"t^{2} = \frac{8}{3}",
             "This gives the squared parameter value directly."),
        step(6, "Take square roots",
             r"t = \pm\sqrt{\frac{8}{3}} = \pm\frac{2\sqrt{6}}{3}",
             "Square roots introduce both positive and negative solutions. Simplifying $\sqrt{8/3} = 2\sqrt{6}/3$."),
        step(7, "Check $dx/dt \neq 0$",
             r"\frac{dx}{dt} = 2 \neq 0 \text{ for all } t",
             "Since $dx/dt$ is never zero, both values of $t$ give valid points on the curve."),
        step(8, "Verify $t = \dfrac{2\sqrt{6}}{3}$",
             r"\frac{3 \cdot \frac{8}{3}}{2} = \frac{8}{2} = 4 \quad \checkmark",
             "Substituting back confirms the positive root gives gradient $4$."),
        step(9, "State the final answer",
             r"t = \pm\frac{2\sqrt{6}}{3}",
             "The curve has gradient $4$ when $t = \pm 2\sqrt{6}/3$."),
    ],
    r"$t = \pm\dfrac{2\sqrt{6}}{3}$.",
))

# ── q042 Intermediate: show that ────────────────────────────────────────────
questions.append(make_q(
    "q042", "Intermediate", 5, "show_that",
    ["parametric differentiation", "show that", "trigonometry"],
    r"A curve has parametric equations $x = \sin t$ and $y = \cos 2t$, where $\cos t \neq 0$. Show that $\dfrac{dy}{dx} = -4\sin t$.",
    [
        step(1, "Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = \cos t",
             "The derivative of $\sin t$ is $\cos t$."),
        step(2, "Differentiate $y$ with respect to $t$",
             r"\frac{dy}{dt} = -2\sin 2t",
             "Using the chain rule on $\cos 2t$ gives $-2\sin 2t$."),
        step(3, "Rewrite $\sin 2t$ using the double-angle identity",
             r"-2\sin 2t = -2(2\sin t \cos t) = -4\sin t \cos t",
             "The identity $\sin 2t = 2\sin t \cos t$ rewrites the derivative in terms of $\sin t$ and $\cos t$."),
        step(4, "Write the parametric formula for $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{dy/dt}{dx/dt}",
             "The gradient is the ratio of the two parametric derivatives."),
        step(5, "Substitute the derivatives",
             r"\frac{dy}{dx} = \frac{-4\sin t \cos t}{\cos t}",
             "Placing $-4\sin t \cos t$ over $\cos t$ sets up the simplification."),
        step(6, "Cancel $\cos t$",
             r"\frac{dy}{dx} = -4\sin t",
             "Since $\cos t \neq 0$, we can cancel $\cos t$ from numerator and denominator."),
        step(7, "Note the domain restriction",
             r"\cos t \neq 0 \Rightarrow t \neq \frac{\pi}{2} + n\pi",
             "The cancellation is valid only where $\cos t \neq 0$, excluding odd multiples of $\pi/2$."),
        step(8, "Alternative check using $x$",
             r"\sin t = x \Rightarrow \frac{dy}{dx} = -4x",
             "Since $\sin t = x$, the gradient can also be written as $-4x$ in Cartesian terms."),
        step(9, "State the result",
             r"\frac{dy}{dx} = -4\sin t",
             "This matches the required result, completing the proof."),
    ],
    r"$\dfrac{dy}{dx} = -4\sin t$, as required.",
))

# ── q043 Intermediate: tangent parallel to x-axis ───────────────────────────
questions.append(make_q(
    "q043", "Intermediate", 5, "coordinates",
    ["parametric differentiation", "horizontal tangent", "stationary points"],
    r"A curve has parametric equations $x = t^{2} - 1$ and $y = t^{3}$, where $t \neq 0$. Find the coordinates of the point at which the tangent is parallel to the $x$-axis.",
    [
        step(1, "Interpret the condition",
             r"\text{Tangent parallel to } x\text{-axis} \Leftrightarrow \frac{dy}{dx} = 0",
             "A horizontal tangent has zero gradient, so we need $\dfrac{dy}{dx} = 0$."),
        step(2, "Differentiate parametrically",
             r"\frac{dx}{dt} = 2t,\qquad \frac{dy}{dt} = 3t^{2}",
             "Both derivatives are needed to form the gradient."),
        step(3, "Write $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{3t^{2}}{2t} = \frac{3t}{2}",
             "Simplifying (using $t \neq 0$) gives a linear expression in $t$."),
        step(4, "Set the gradient to zero",
             r"\frac{3t}{2} = 0 \Rightarrow t = 0",
             "The only solution is $t = 0$."),
        step(5, "Find the coordinates at $t = 0$",
             r"x = 0^{2} - 1 = -1,\quad y = 0^{3} = 0 \Rightarrow (-1,\, 0)",
             "Substituting $t = 0$ gives the point $(-1, 0)$."),
        step(6, "Note that $t = 0$ was excluded from simplification",
             r"\text{At } t = 0:\ \frac{dy}{dx} = \frac{0}{0} \text{ (indeterminate form)}",
             "Direct substitution into the unsimplified fraction gives $0/0$, so we must check separately."),
        step(7, "Evaluate the limit as $t \to 0$",
             r"\lim_{t \to 0} \frac{3t^{2}}{2t} = \lim_{t \to 0} \frac{3t}{2} = 0",
             "Taking the limit confirms the gradient approaches zero at $t = 0$."),
        step(8, "Confirm the tangent is horizontal",
             r"\frac{dy}{dx} = 0 \text{ at } (-1,\, 0)",
             "A zero gradient means the tangent line is indeed parallel to the $x$-axis."),
        step(9, "State the final answer",
             r"(-1,\, 0)",
             "The tangent is horizontal at the point $(-1, 0)$."),
    ],
    r"The tangent is parallel to the $x$-axis at $(-1,\, 0)$.",
))

# ── q044 Intermediate: second derivative at a point (trig) ─────────────────
sqrt2 = math.sqrt(2)
csc3 = -(sqrt2) ** 3  # -2*sqrt(2)

questions.append(make_q(
    "q044", "Intermediate", 6, "value",
    ["parametric differentiation", "second derivative", "trigonometry"],
    r"A curve has parametric equations $x = \cos t$ and $y = \sin t$, where $0 < t < \pi$. Find the exact value of $\dfrac{d^{2}y}{dx^{2}}$ when $t = \dfrac{\pi}{4}$.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             r"\frac{dx}{dt} = -\sin t,\qquad \frac{dy}{dt} = \cos t",
             "These are the standard derivatives of $\cos t$ and $\sin t$."),
        step(2, "Find the first derivative $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{\cos t}{-\sin t} = -\cot t",
             "Dividing gives $-\cot t$, the gradient of the unit circle in parametric form."),
        step(3, "Recall the second-derivative formula",
             r"\frac{d^{2}y}{dx^{2}} = \frac{\dfrac{d}{dt}\!\left(\dfrac{dy}{dx}\right)}{\dfrac{dx}{dt}}",
             "Differentiate the first derivative with respect to $t$, then divide by $dx/dt$."),
        step(4, "Differentiate $-\cot t$ with respect to $t$",
             r"\frac{d}{dt}(-\cot t) = \csc^{2} t",
             "The derivative of $\cot t$ is $-\csc^{2} t$, so with the minus sign we get $\csc^{2} t$."),
        step(5, "Form $\dfrac{d^{2}y}{dx^{2}}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{\csc^{2} t}{-\sin t} = -\csc^{3} t",
             "Dividing by $-\sin t$ combines the two $\sin t$ factors into $\csc^{3} t$."),
        step(6, "Substitute $t = \dfrac{\pi}{4}$",
             r"\sin\frac{\pi}{4} = \frac{\sqrt{2}}{2} \Rightarrow \csc\frac{\pi}{4} = \sqrt{2}",
             "At $t = \pi/4$, $\sin t = \cos t = \sqrt{2}/2$, so $\csc t = \sqrt{2}$."),
        step(7, "Evaluate $\csc^{3} t$",
             r"-\csc^{3}\!\frac{\pi}{4} = -(\sqrt{2})^{3} = -2\sqrt{2}",
             "Cubing $\sqrt{2}$ gives $2\sqrt{2}$, and the leading minus sign remains."),
        step(8, "Interpret the sign",
             r"\frac{d^{2}y}{dx^{2}} < 0",
             "A negative second derivative at this point indicates the curve is concave down there."),
        step(9, "Connect to the circle",
             r"\text{The upper semicircle bends downward (concave down)}",
             "On the upper half of the unit circle, the curve arches downward, consistent with a negative second derivative."),
        step(10, "State the final answer",
             r"\frac{d^{2}y}{dx^{2}} = -2\sqrt{2}",
             "The exact value of the second derivative at $t = \pi/4$ is $-2\sqrt{2}$."),
    ],
    r"$\dfrac{d^{2}y}{dx^{2}} = -2\sqrt{2}$ when $t = \dfrac{\pi}{4}$.",
))

# ── q045 Intermediate: multi-part stationary points ───────────────────────
questions.append(make_q(
    "q045", "Intermediate", 7, "multi_part",
    ["parametric differentiation", "stationary points", "multi-part"],
    r"A curve $C$ has parametric equations $x = t^{2} + 1$ and $y = 2t^{3} - 6t$, where $t \neq 0$.\n\n**(a)** Find $\dfrac{dy}{dx}$ in terms of $t$.\n\n**(b)** Hence find the coordinates of the stationary points on $C$.",
    [
        step(1, "(a) Differentiate $x$ and $y$ with respect to $t$",
             r"\frac{dx}{dt} = 2t,\qquad \frac{dy}{dt} = 6t^{2} - 6",
             "Both parametric derivatives are needed for part (a)."),
        step(2, "(a) Form $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{6t^{2} - 6}{2t} = \frac{3(t^{2} - 1)}{t}",
             "Dividing and factoring gives a compact expression for the gradient."),
        step(3, "(a) State the result for part (a)",
             r"\frac{dy}{dx} = \frac{3(t^{2} - 1)}{t}",
             "This is the gradient in terms of $t$, valid for $t \neq 0$."),
        step(4, "(b) Set the gradient to zero",
             r"6t^{2} - 6 = 0",
             "For a stationary point, the numerator of $\dfrac{dy}{dx}$ must be zero (since $t \neq 0$)."),
        step(5, "(b) Solve for $t$",
             r"t^{2} = 1 \Rightarrow t = \pm 1",
             "Both values satisfy $t \neq 0$."),
        step(6, "(b) Find coordinates when $t = 1$",
             r"x = 1 + 1 = 2,\quad y = 2 - 6 = -4 \Rightarrow (2,\, -4)",
             "Substituting $t = 1$ into both parametric equations."),
        step(7, "(b) Find coordinates when $t = -1$",
             r"x = 1 + 1 = 2,\quad y = -2 + 6 = 4 \Rightarrow (2,\, 4)",
             "Substituting $t = -1$ gives the second stationary point."),
        step(8, "Verify $dx/dt \neq 0$",
             r"t = \pm 1 \Rightarrow \frac{dx}{dt} = \pm 2 \neq 0",
             "Both parameter values give valid stationary points."),
        step(9, "Summarise both parts",
             r"\text{(a) } \frac{dy}{dx} = \frac{3(t^{2}-1)}{t};\quad \text{(b) stationary points: } (2,-4),\ (2,4)",
             "Part (b) used the result from part (a) directly by setting the numerator to zero."),
        step(10, "State the final answer",
             r"\frac{dy}{dx} = \frac{3(t^{2}-1)}{t};\quad (2,\,-4) \text{ and } (2,\,4)",
             "The gradient formula and two stationary points complete both parts."),
    ],
    r"**(a)** $\dfrac{dy}{dx} = \dfrac{3(t^{2}-1)}{t}$. **(b)** The stationary points are $(2,\,-4)$ and $(2,\,4)$.",
))

# ── q046 Hard: second derivative at t=0 (exponential) ─────────────────────
questions.append(make_q(
    "q046", "Hard", 7, "value",
    ["parametric differentiation", "second derivative", "exponential"],
    r"A curve has parametric equations $x = e^{t}$ and $y = te^{t}$. Find the exact value of $\dfrac{d^{2}y}{dx^{2}}$ at the point where $t = 0$.",
    [
        step(1, "Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = e^{t}",
             "The derivative of $e^{t}$ is $e^{t}$ itself."),
        step(2, "Differentiate $y$ using the product rule",
             r"\frac{dy}{dt} = e^{t} + te^{t} = e^{t}(1 + t)",
             "For $te^{t}$, the product rule gives $e^{t} + te^{t}$, which factors neatly."),
        step(3, "Find the first derivative $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{e^{t}(1+t)}{e^{t}} = 1 + t",
             "The factor $e^{t}$ cancels, leaving a simple linear expression."),
        step(4, "Recall the second-derivative formula",
             r"\frac{d^{2}y}{dx^{2}} = \frac{\dfrac{d}{dt}\!\left(\dfrac{dy}{dx}\right)}{\dfrac{dx}{dt}}",
             "Differentiate $\dfrac{dy}{dx}$ with respect to $t$, then divide by $dx/dt$."),
        step(5, "Differentiate $\dfrac{dy}{dx} = 1 + t$ with respect to $t$",
             r"\frac{d}{dt}(1 + t) = 1",
             "The derivative of the linear expression is the constant $1$."),
        step(6, "Form $\dfrac{d^{2}y}{dx^{2}}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{1}{e^{t}} = e^{-t}",
             "Dividing $1$ by $e^{t}$ gives $e^{-t}$."),
        step(7, "Substitute $t = 0$",
             r"\left.\frac{d^{2}y}{dx^{2}}\right|_{t=0} = e^{0} = 1",
             "At $t = 0$, the second derivative equals $1$."),
        step(8, "Find the coordinates at $t = 0$",
             r"x = e^{0} = 1,\quad y = 0 \Rightarrow (1,\, 0)",
             "The point on the curve is $(1, 0)$."),
        step(9, "Verify the first derivative at $t = 0$",
             r"\left.\frac{dy}{dx}\right|_{t=0} = 1 + 0 = 1",
             "At the origin of the parameter, the tangent has gradient $1$."),
        step(10, "Interpret the second derivative",
             r"\frac{d^{2}y}{dx^{2}} = 1 > 0 \text{ at } (1,\, 0)",
             "A positive second derivative means the curve is concave up at $(1, 0)$."),
        step(11, "Connect to Cartesian form",
             r"x = e^{t} \Rightarrow t = \ln x;\quad y = x\ln x",
             "Eliminating $t$ gives $y = x\ln x$, whose second derivative confirms the result."),
        step(12, "Differentiate $y = x\ln x$ to confirm",
             r"\frac{dy}{dx} = \ln x + 1;\quad \frac{d^{2}y}{dx^{2}} = \frac{1}{x}",
             "In Cartesian form, the second derivative is $1/x$. At $x = 1$ (i.e. $t = 0$), this equals $1$."),
        step(13, "State the final answer",
             r"\frac{d^{2}y}{dx^{2}} = 1",
             "The exact value of the second derivative at $t = 0$ is $1$."),
    ],
    r"$\dfrac{d^{2}y}{dx^{2}} = 1$ at $t = 0$.",
))

# ── q047 Hard: normal through fixed point ───────────────────────────────────
questions.append(make_q(
    "q047", "Hard", 7, "value",
    ["parametric differentiation", "normal", "find parameter"],
    r"A curve has parametric equations $x = t^{2}$ and $y = 2t$, where $t \neq 0$. The normal to the curve at a point $P$ passes through the point $(4,\, 0)$. Find the possible values of $t$.",
    [
        step(1, "Differentiate parametrically",
             r"\frac{dx}{dt} = 2t,\qquad \frac{dy}{dt} = 2",
             "Both derivatives are needed to find the tangent gradient."),
        step(2, "Find $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{2}{2t} = \frac{1}{t}",
             "The tangent gradient at parameter $t$ is $1/t$."),
        step(3, "Find the gradient of the normal",
             r"m_{\text{normal}} = -\frac{1}{\dfrac{dy}{dx}} = -t",
             "The normal gradient is the negative reciprocal of the tangent gradient."),
        step(4, "Write coordinates of $P$",
             r"P = (t^{2},\; 2t)",
             "The point on the curve at parameter $t$ has coordinates $(t^{2}, 2t)$."),
        step(5, "Write the equation of the normal through $P$",
             r"y - 2t = -t(x - t^{2})",
             "Using point-gradient form with gradient $-t$."),
        step(6, "Substitute the point $(4,\, 0)$",
             r"0 - 2t = -t(4 - t^{2})",
             "Since the normal passes through $(4, 0)$, we set $x = 4$ and $y = 0$."),
        step(7, "Expand the right-hand side",
             r"-2t = -4t + t^{3}",
             "Distributing $-t$ across $(4 - t^{2})$ gives $-4t + t^{3}$."),
        step(8, "Rearrange and factorise",
             r"0 = -2t + t^{3} \Rightarrow t^{3} - 2t = 0 \Rightarrow t(t^{2} - 2) = 0",
             "Collecting all terms on one side and factoring out $t$."),
        step(9, "Solve for $t$",
             r"t = 0 \quad \text{or} \quad t^{2} = 2",
             "Setting each factor to zero gives the candidate values."),
        step(10, "Reject $t = 0$",
             r"t \neq 0 \text{ (given)}",
             "The question specifies $t \neq 0$, so we exclude $t = 0$."),
        step(11, "Find the valid parameter values",
             r"t = \pm\sqrt{2}",
             "Taking square roots of $t^{2} = 2$ gives two valid solutions."),
        step(12, "Verify for $t = \sqrt{2}$",
             r"P = (2,\, 2\sqrt{2});\quad 0 - 2\sqrt{2} = -\sqrt{2}(4 - 2) = -2\sqrt{2} \quad \checkmark",
             "Substituting $t = \sqrt{2}$ confirms the normal passes through $(4, 0)$."),
        step(13, "Verify for $t = -\sqrt{2}$",
             r"P = (2,\, -2\sqrt{2});\quad 0 + 2\sqrt{2} = \sqrt{2}(4 - 2) = 2\sqrt{2} \quad \checkmark",
             "The negative root also satisfies the condition."),
        step(14, "State the final answer",
             r"t = \pm\sqrt{2}",
             "The normal passes through $(4, 0)$ when $t = \pm\sqrt{2}$."),
    ],
    r"$t = \pm\sqrt{2}$.",
))

# ── q048 Hard: show that second derivative ──────────────────────────────────
questions.append(make_q(
    "q048", "Hard", 8, "show_that",
    ["parametric differentiation", "second derivative", "show that"],
    r"A curve has parametric equations $x = 2t$ and $y = t^{2} + \dfrac{1}{t}$, where $t \neq 0$. Show that $\dfrac{d^{2}y}{dx^{2}} = \dfrac{1}{2}\left(1 + \dfrac{1}{t^{3}}\right)$.",
    [
        step(1, "Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = 2",
             "The $x$-equation is linear, giving a constant derivative."),
        step(2, "Differentiate $y$ with respect to $t$",
             r"\frac{dy}{dt} = 2t - \frac{1}{t^{2}}",
             "Differentiating $t^{2} + t^{-1}$ gives $2t - t^{-2}$."),
        step(3, "Find the first derivative $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{2t - \frac{1}{t^{2}}}{2} = t - \frac{1}{2t^{2}}",
             "Dividing $dy/dt$ by $dx/dt = 2$ gives the gradient."),
        step(4, "Recall the second-derivative formula",
             r"\frac{d^{2}y}{dx^{2}} = \frac{\dfrac{d}{dt}\!\left(\dfrac{dy}{dx}\right)}{\dfrac{dx}{dt}}",
             "Differentiate the first derivative with respect to $t$, then divide by $2$."),
        step(5, "Differentiate $\dfrac{dy}{dx}$ with respect to $t$",
             r"\frac{d}{dt}\!\left(t - \frac{1}{2t^{2}}\right) = 1 + \frac{1}{t^{3}}",
             "The derivative of $t$ is $1$, and the derivative of $-\frac{1}{2}t^{-2}$ is $t^{-3}$."),
        step(6, "Divide by $\dfrac{dx}{dt}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{1 + \frac{1}{t^{3}}}{2}",
             "Dividing by $2$ completes the parametric second-derivative calculation."),
        step(7, "Write in the required form",
             r"\frac{d^{2}y}{dx^{2}} = \frac{1}{2}\left(1 + \frac{1}{t^{3}}\right)",
             "Factoring out $1/2$ matches the expression to be shown."),
        step(8, "Check the sign at $t = 1$",
             r"\left.\frac{d^{2}y}{dx^{2}}\right|_{t=1} = \frac{1}{2}(1 + 1) = 1 > 0",
             "At $t = 1$ the second derivative is positive, indicating concavity upward."),
        step(9, "Note where the expression is undefined",
             r"t \neq 0",
             "The term $1/t^{3}$ requires $t \neq 0$, consistent with the domain of the curve."),
        step(10, "Connect to the reciprocal term in $y$",
             r"\text{The } \frac{1}{t} \text{ term in } y \text{ introduces the } \frac{1}{t^{3}} \text{ in the second derivative}",
             "The reciprocal in $y$ propagates through differentiation, appearing cubed in the second derivative."),
        step(11, "Alternative form",
             r"\frac{d^{2}y}{dx^{2}} = \frac{t^{3} + 1}{2t^{3}}",
             "Combining over a common denominator gives an equivalent single fraction."),
        step(12, "State the result",
             r"\frac{d^{2}y}{dx^{2}} = \frac{1}{2}\left(1 + \frac{1}{t^{3}}\right)",
             "This matches the required result, completing the proof."),
        step(13, "Confirm equivalence of the two forms",
             r"\frac{1}{2}\left(1 + \frac{1}{t^{3}}\right) = \frac{t^{3} + 1}{2t^{3}}",
             "Writing over a common denominator shows the two expressions are identical."),
    ],
    r"$\dfrac{d^{2}y}{dx^{2}} = \dfrac{1}{2}\left(1 + \dfrac{1}{t^{3}}\right)$, as required.",
))

# ── q049 Hard: stationary points and nature ─────────────────────────────────
questions.append(make_q(
    "q049", "Hard", 9, "multi_part",
    ["parametric differentiation", "stationary points", "second derivative test"],
    r"A curve $C$ has parametric equations $x = t^{3} - 3t$ and $y = t^{2}$, where $|t| \neq 1$.\n\n**(a)** Find $\dfrac{dy}{dx}$ in terms of $t$.\n\n**(b)** Find the coordinates of the stationary point on $C$.\n\n**(c)** Determine whether this stationary point is a local maximum or a local minimum.",
    [
        step(1, "(a) Differentiate $x$ and $y$ with respect to $t$",
             r"\frac{dx}{dt} = 3t^{2} - 3 = 3(t^{2} - 1),\qquad \frac{dy}{dt} = 2t",
             "Both parametric derivatives are needed."),
        step(2, "(a) Form $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{2t}{3(t^{2} - 1)}",
             "Dividing gives the gradient in terms of $t$, valid where $t^{2} \neq 1$."),
        step(3, "(b) Set the numerator equal to zero",
             r"2t = 0 \Rightarrow t = 0",
             "A stationary point requires $\dfrac{dy}{dx} = 0$, so the numerator $2t$ must be zero."),
        step(4, "(b) Check $dx/dt \neq 0$ at $t = 0$",
             r"\left.\frac{dx}{dt}\right|_{t=0} = -3 \neq 0",
             "Since $dx/dt \neq 0$, the stationary-point condition is valid at $t = 0$."),
        step(5, "(b) Find the coordinates",
             r"x = 0,\quad y = 0 \Rightarrow (0,\, 0)",
             "Substituting $t = 0$ gives the stationary point at the origin."),
        step(6, "(c) Differentiate $\dfrac{dy}{dx}$ with respect to $t$",
             r"\frac{d}{dt}\!\left(\frac{2t}{3(t^{2}-1)}\right) = \frac{-6(t^{2}+1)}{9(t^{2}-1)^{2}} = \frac{-2(t^{2}+1)}{3(t^{2}-1)^{2}}",
             "Using the quotient rule on the first derivative."),
        step(7, "(c) Form $\dfrac{d^{2}y}{dx^{2}}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{-2(t^{2}+1)}{3(t^{2}-1)^{2}} \div 3(t^{2}-1) = \frac{-2(t^{2}+1)}{9(t^{2}-1)^{3}}",
             "Dividing by $dx/dt = 3(t^{2}-1)$."),
        step(8, "(c) Evaluate at $t = 0$",
             r"\left.\frac{d^{2}y}{dx^{2}}\right|_{t=0} = \frac{-2(1)}{9(-1)^{3}} = \frac{-2}{-9} = \frac{2}{9}",
             "Substituting $t = 0$ gives a positive second derivative."),
        step(9, "(c) Apply the second-derivative test",
             r"\frac{d^{2}y}{dx^{2}} = \frac{2}{9} > 0 \Rightarrow \text{local minimum}",
             "A positive second derivative at a stationary point means the curve is concave up there, so the point is a local minimum."),
        step(10, "Summarise part (a)",
             r"\frac{dy}{dx} = \frac{2t}{3(t^{2}-1)}",
             "The gradient formula is valid for $|t| \neq 1$."),
        step(11, "Summarise part (b)",
             r"\text{Stationary point: } (0,\, 0)",
             "There is exactly one stationary point on the curve."),
        step(12, "Summarise part (c)",
             r"(0,\, 0) \text{ is a local minimum}",
             "The second-derivative test confirms the nature of the stationary point."),
        step(13, "State the final answer",
             r"\text{(a) } \frac{2t}{3(t^{2}-1)};\quad \text{(b) } (0,0);\quad \text{(c) local minimum}",
             "All three parts are now complete."),
    ],
    r"**(a)** $\dfrac{dy}{dx} = \dfrac{2t}{3(t^{2}-1)}$. **(b)** Stationary point: $(0,\,0)$. **(c)** Local minimum.",
))

# ── q050 Hard: normal with specific gradient ────────────────────────────────
questions.append(make_q(
    "q050", "Hard", 7, "value",
    ["parametric differentiation", "normal", "gradient condition"],
    r"A curve has parametric equations $x = t^{2}$ and $y = t^{3}$, where $t \neq 0$. Find the value of $t$ for which the normal to the curve has gradient $-\dfrac{1}{2}$.",
    [
        step(1, "Differentiate parametrically",
             r"\frac{dx}{dt} = 2t,\qquad \frac{dy}{dt} = 3t^{2}",
             "Both derivatives are needed to find the tangent gradient."),
        step(2, "Find $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{3t^{2}}{2t} = \frac{3t}{2}",
             "Simplifying (using $t \neq 0$) gives $3t/2$."),
        step(3, "Write the normal gradient in terms of $t$",
             r"m_{\text{normal}} = -\frac{1}{\dfrac{dy}{dx}} = -\frac{2}{3t}",
             "The normal gradient is the negative reciprocal of the tangent gradient."),
        step(4, "Set the normal gradient equal to $-\dfrac{1}{2}$",
             r"-\frac{2}{3t} = -\frac{1}{2}",
             "The question specifies that the normal has gradient $-1/2$."),
        step(5, "Multiply both sides by $-1$",
             r"\frac{2}{3t} = \frac{1}{2}",
             "Removing the negative signs simplifies the equation."),
        step(6, "Cross-multiply",
             r"4 = 3t",
             "Cross-multiplying $2 \cdot 2 = 3t \cdot 1$ gives $4 = 3t$."),
        step(7, "Solve for $t$",
             r"t = \frac{4}{3}",
             "Dividing by $3$ gives the parameter value."),
        step(8, "Verify the tangent gradient at $t = \dfrac{4}{3}$",
             r"\frac{dy}{dx} = \frac{3 \cdot \frac{4}{3}}{2} = 2",
             "The tangent gradient is $2$, so the normal gradient is $-1/2$."),
        step(9, "Find the coordinates of the point",
             r"x = \frac{16}{9},\quad y = \frac{64}{27}",
             "Substituting $t = 4/3$ gives the point where the condition holds."),
        step(10, "Check $dx/dt \neq 0$",
             r"\frac{dx}{dt} = \frac{8}{3} \neq 0",
             "The parameter value gives a valid point on the curve."),
        step(11, "Confirm the normal gradient",
             r"m_{\text{normal}} = -\frac{2}{3 \cdot \frac{4}{3}} = -\frac{2}{4} = -\frac{1}{2} \quad \checkmark",
             "Substituting back confirms the normal has the required gradient."),
        step(12, "State the final answer",
             r"t = \frac{4}{3}",
             "The normal has gradient $-1/2$ when $t = 4/3$."),
        step(13, "Interpret geometrically",
             r"\text{At } t = \frac{4}{3}\text{, the tangent is steeper than the normal}",
             "A tangent gradient of $2$ compared with a normal gradient of $-1/2$ reflects the perpendicular relationship."),
    ],
    r"$t = \dfrac{4}{3}$.",
))

# ── q051 Hard: multi-part with first and second derivative ──────────────────
questions.append(make_q(
    "q051", "Hard", 10, "multi_part",
    ["parametric differentiation", "first derivative", "second derivative", "multi-part"],
    r"A curve $C$ has parametric equations $x = t + \dfrac{1}{t}$ and $y = t - \dfrac{1}{t}$, where $t \neq 0$.\n\n**(a)** Show that $\dfrac{dy}{dx} = \dfrac{t^{2} + 1}{t^{2} - 1}$.\n\n**(b)** Hence show that $\dfrac{d^{2}y}{dx^{2}} = \dfrac{-4t^{3}}{(t^{2} - 1)^{3}}$.",
    [
        step(1, "(a) Differentiate $x$ with respect to $t$",
             r"\frac{dx}{dt} = 1 - \frac{1}{t^{2}} = \frac{t^{2} - 1}{t^{2}}",
             "Rewriting over a common denominator prepares for the ratio."),
        step(2, "(a) Differentiate $y$ with respect to $t$",
             r"\frac{dy}{dt} = 1 + \frac{1}{t^{2}} = \frac{t^{2} + 1}{t^{2}}",
             "Similarly, $dy/dt$ simplifies to a single fraction."),
        step(3, "(a) Form $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{\dfrac{t^{2}+1}{t^{2}}}{\dfrac{t^{2}-1}{t^{2}}} = \frac{t^{2} + 1}{t^{2} - 1}",
             "The factor $t^{2}$ cancels from numerator and denominator."),
        step(4, "(a) Note the domain restriction",
             r"t^{2} \neq 1 \Rightarrow t \neq \pm 1",
             "The gradient is undefined when $t^{2} = 1$, i.e. at $t = \pm 1$."),
        step(5, "(b) Recall the second-derivative formula",
             r"\frac{d^{2}y}{dx^{2}} = \frac{\dfrac{d}{dt}\!\left(\dfrac{dy}{dx}\right)}{\dfrac{dx}{dt}}",
             "We differentiate the result from part (a) with respect to $t$, then divide by $dx/dt$."),
        step(6, "(b) Differentiate $\dfrac{dy}{dx}$ using the quotient rule",
             r"\frac{d}{dt}\!\left(\frac{t^{2}+1}{t^{2}-1}\right) = \frac{2t(t^{2}-1) - (t^{2}+1)(2t)}{(t^{2}-1)^{2}}",
             "Applying the quotient rule with $u = t^{2}+1$ and $v = t^{2}-1$."),
        step(7, "(b) Simplify the numerator",
             r"2t(t^{2}-1) - 2t(t^{2}+1) = 2t(-2) = -4t",
             "Expanding and collecting like terms leaves $-4t$ in the numerator."),
        step(8, "(b) Write $\dfrac{d}{dt}\!\left(\dfrac{dy}{dx}\right)$",
             r"\frac{d}{dt}\!\left(\frac{dy}{dx}\right) = \frac{-4t}{(t^{2}-1)^{2}}",
             "This is the derivative of the first derivative with respect to $t$."),
        step(9, "(b) Divide by $\dfrac{dx}{dt}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{-4t}{(t^{2}-1)^{2}} \div \frac{t^{2}-1}{t^{2}}",
             "Dividing by $dx/dt$ completes the parametric second derivative."),
        step(10, "(b) Multiply by the reciprocal",
             r"\frac{d^{2}y}{dx^{2}} = \frac{-4t}{(t^{2}-1)^{2}} \times \frac{t^{2}}{t^{2}-1} = \frac{-4t^{3}}{(t^{2}-1)^{3}}",
             "Multiplying by the reciprocal of $dx/dt$ and combining powers gives the final form."),
        step(11, "Verify at $t = 2$",
             r"\left.\frac{d^{2}y}{dx^{2}}\right|_{t=2} = \frac{-32}{27}",
             "A numerical check at $t = 2$ confirms the expression is consistent."),
        step(12, "State part (a) result",
             r"\frac{dy}{dx} = \frac{t^{2} + 1}{t^{2} - 1}",
             "Part (a) is proved."),
        step(13, "State part (b) result",
             r"\frac{d^{2}y}{dx^{2}} = \frac{-4t^{3}}{(t^{2}-1)^{3}}",
             "Part (b) is proved, completing both parts."),
    ],
    r"**(a)** $\dfrac{dy}{dx} = \dfrac{t^{2}+1}{t^{2}-1}$. **(b)** $\dfrac{d^{2}y}{dx^{2}} = \dfrac{-4t^{3}}{(t^{2}-1)^{3}}$.",
))

# ── q052 Hard: tangent, normal, y-intercept ─────────────────────────────────
questions.append(make_q(
    "q052", "Hard", 8, "multi_part",
    ["parametric differentiation", "tangent", "normal", "multi-part"],
    r"A curve has parametric equations $x = 3t$ and $y = t^{2} + 2$.\n\n**(a)** Find the gradient of the curve at the point where $t = 1$.\n\n**(b)** Find the equation of the normal to the curve at this point, giving your answer in the form $y = mx + c$.\n\n**(c)** Hence find the $y$-coordinate of the point where this normal crosses the $y$-axis.",
    [
        step(1, "(a) Differentiate parametrically",
             r"\frac{dx}{dt} = 3,\qquad \frac{dy}{dt} = 2t",
             "Both derivatives are needed to find the gradient."),
        step(2, "(a) Form $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{2t}{3}",
             "Dividing $dy/dt$ by $dx/dt$ gives the gradient as a function of $t$."),
        step(3, "(a) Evaluate at $t = 1$",
             r"\left.\frac{dy}{dx}\right|_{t=1} = \frac{2}{3}",
             "Substituting $t = 1$ gives the gradient at the required point."),
        step(4, "(b) Find the coordinates at $t = 1$",
             r"x = 3,\quad y = 3 \Rightarrow (3,\, 3)",
             "The point on the curve is $(3, 3)$."),
        step(5, "(b) Find the normal gradient",
             r"m_{\text{normal}} = -\frac{3}{2}",
             "The normal gradient is the negative reciprocal of $2/3$."),
        step(6, "(b) Write the normal equation",
             r"y - 3 = -\frac{3}{2}(x - 3)",
             "Using point-gradient form with point $(3, 3)$ and gradient $-3/2$."),
        step(7, "(b) Rearrange to $y = mx + c$",
             r"y = -\frac{3}{2}x + \frac{9}{2} + 3 = -\frac{3}{2}x + \frac{15}{2}",
             "Expanding and simplifying gives the equation in the required form."),
        step(8, "(c) Find the $y$-intercept",
             r"x = 0 \Rightarrow y = \frac{15}{2}",
             "On the $y$-axis, $x = 0$, so substituting into the normal equation."),
        step(9, "Verify the normal passes through $(3, 3)$",
             r"y = -\frac{9}{2} + \frac{15}{2} = 3 \quad \checkmark",
             "Substituting $x = 3$ confirms the line passes through the curve point."),
        step(10, "Verify the tangent gradient",
             r"\text{Tangent gradient } = \frac{2}{3};\quad m_{\text{normal}} \times \frac{2}{3} = -1 \quad \checkmark",
             "The product of perpendicular gradients is $-1$, confirming the normal is correct."),
        step(11, "Interpret part (c)",
             r"\text{The normal crosses the } y\text{-axis at } \left(0,\, \frac{15}{2}\right)",
             "The $y$-intercept is the value of $y$ when $x = 0$."),
        step(12, "State the final answer",
             r"\text{(a) } \frac{2}{3};\quad \text{(b) } y = -\frac{3}{2}x + \frac{15}{2};\quad \text{(c) } \frac{15}{2}",
             "All three parts are complete."),
        step(13, "Summarise the geometry",
             r"\text{Normal passes through } (3,3),\ (0,\,\frac{15}{2})",
             "The normal line connects the curve point to its $y$-axis intercept."),
    ],
    r"**(a)** $\dfrac{2}{3}$. **(b)** $y = -\dfrac{3}{2}x + \dfrac{15}{2}$. **(c)** The $y$-coordinate is $\dfrac{15}{2}$.",
))

# ── q053 Hard: full exam multi-part ─────────────────────────────────────────
questions.append(make_q(
    "q053", "Hard", 12, "multi_part",
    ["parametric differentiation", "stationary points", "second derivative test", "multi-part"],
    r"A curve $C$ has parametric equations $x = t^{2}$ and $y = t^{3} - 6t$, where $t \neq 0$.\n\n**(a)** Show that $\dfrac{dy}{dx} = \dfrac{3(t^{2} - 2)}{2t}$.\n\n**(b)** Find the coordinates of the stationary points on $C$.\n\n**(c)** Show that $\dfrac{d^{2}y}{dx^{2}} = \dfrac{3(t^{2} + 2)}{4t^{3}}$.\n\n**(d)** Hence determine the nature of each stationary point.",
    [
        step(1, "(a) Differentiate $x$ and $y$ with respect to $t$",
             r"\frac{dx}{dt} = 2t,\qquad \frac{dy}{dt} = 3t^{2} - 6",
             "Both parametric derivatives are required."),
        step(2, "(a) Form $\dfrac{dy}{dx}$",
             r"\frac{dy}{dx} = \frac{3t^{2} - 6}{2t} = \frac{3(t^{2} - 2)}{2t}",
             "Factoring $3$ from the numerator gives the required form."),
        step(3, "(b) Set the numerator equal to zero",
             r"3t^{2} - 6 = 0 \Rightarrow t^{2} = 2",
             "Stationary points occur when $\dfrac{dy}{dx} = 0$, so the numerator must vanish."),
        step(4, "(b) Solve for $t$",
             r"t = \pm\sqrt{2}",
             "Both values satisfy $t \neq 0$."),
        step(5, "(b) Find coordinates when $t = \sqrt{2}$",
             r"x = 2,\quad y = 2\sqrt{2} - 6\sqrt{2} = -4\sqrt{2} \Rightarrow (2,\, -4\sqrt{2})",
             "Substituting $t = \sqrt{2}$ into both parametric equations."),
        step(6, "(b) Find coordinates when $t = -\sqrt{2}$",
             r"x = 2,\quad y = -2\sqrt{2} + 6\sqrt{2} = 4\sqrt{2} \Rightarrow (2,\, 4\sqrt{2})",
             "Substituting $t = -\sqrt{2}$ gives the second stationary point."),
        step(7, "(c) Differentiate $\dfrac{dy}{dx}$ using the quotient rule",
             r"\frac{d}{dt}\!\left(\frac{3t^{2}-6}{2t}\right) = \frac{6t(2t) - 2(3t^{2}-6)}{4t^{2}} = \frac{12t^{2} - 6t^{2} + 12}{4t^{2}} = \frac{3(t^{2}+2)}{2t^{2}}",
             "The quotient rule simplifies to $3(t^{2}+2)/(2t^{2})$."),
        step(8, "(c) Form $\dfrac{d^{2}y}{dx^{2}}$",
             r"\frac{d^{2}y}{dx^{2}} = \frac{3(t^{2}+2)}{2t^{2}} \div 2t = \frac{3(t^{2}+2)}{4t^{3}}",
             "Dividing by $dx/dt = 2t$ gives the second derivative."),
        step(9, "(d) Evaluate at $t = \sqrt{2}$",
             r"\left.\frac{d^{2}y}{dx^{2}}\right|_{t=\sqrt{2}} = \frac{3(4)}{4 \cdot 2\sqrt{2}} = \frac{12}{8\sqrt{2}} = \frac{3}{2\sqrt{2}} > 0",
             "A positive second derivative indicates a local minimum."),
        step(10, "(d) Evaluate at $t = -\sqrt{2}$",
             r"\left.\frac{d^{2}y}{dx^{2}}\right|_{t=-\sqrt{2}} = \frac{3(4)}{4 \cdot (-2\sqrt{2})} = -\frac{3}{2\sqrt{2}} < 0",
             "A negative second derivative indicates a local maximum."),
        step(11, "(d) State the nature of each point",
             r"(2,\, -4\sqrt{2}) \text{ is a local minimum};\quad (2,\, 4\sqrt{2}) \text{ is a local maximum}",
             "The second-derivative test gives opposite conclusions at the two parameter values."),
        step(12, "Note both points share $x = 2$",
             r"x = t^{2} = 2 \text{ for both } t = \pm\sqrt{2}",
             "The curve folds back on itself vertically, giving two stationary points at the same $x$-coordinate."),
        step(13, "Verify $dx/dt \neq 0$ at both values",
             r"t = \pm\sqrt{2} \Rightarrow \frac{dx}{dt} = \pm 2\sqrt{2} \neq 0",
             "Both stationary points are valid since $x$ is changing at those parameter values."),
        step(14, "Summarise all parts",
             r"\text{(a) shown; (b) } (2,-4\sqrt{2}),\ (2,4\sqrt{2});\ \text{(c) shown; (d) min and max}",
             "All four parts of this exam-style question are complete."),
        step(15, "State the final answer",
             r"\text{(a)(c) as shown; (b) } (2,\,-4\sqrt{2}),\ (2,\,4\sqrt{2});\ \text{(d) minimum and maximum}",
             "The full solution covers gradient, stationary points, second derivative, and their nature."),
    ],
    r"**(a)** $\dfrac{dy}{dx} = \dfrac{3(t^{2}-2)}{2t}$. **(b)** $(2,\,-4\sqrt{2})$ and $(2,\,4\sqrt{2})$. **(c)** $\dfrac{d^{2}y}{dx^{2}} = \dfrac{3(t^{2}+2)}{4t^{3}}$. **(d)** $(2,\,-4\sqrt{2})$ is a local minimum; $(2,\,4\sqrt{2})$ is a local maximum.",
))

# ── Write output ────────────────────────────────────────────────────────────
OUT = "/Users/benjaminwalpole/Wisest_Maths_V5/wisest-maths-content/src/data/questions/a-level-maths/year-2-pure/parametric-differentiation-q036-q053.ts"
os.makedirs(os.path.dirname(OUT), exist_ok=True)

assert len(questions) == 18, f"Expected 18 questions, got {len(questions)}"

intermediate = sum(1 for q in questions if q["difficulty"] == "Intermediate")
hard = sum(1 for q in questions if q["difficulty"] == "Hard")
assert intermediate == 10, f"Expected 10 Intermediate, got {intermediate}"
assert hard == 8, f"Expected 8 Hard, got {hard}"

for q in questions:
    n = len(q["workedSolution"]["steps"])
    if q["difficulty"] == "Intermediate":
        assert 9 <= n <= 13, f"{q['id']}: Intermediate has {n} steps"
    else:
        assert 13 <= n <= 18, f"{q['id']}: Hard has {n} steps"

write_questions_ts(
    OUT,
    questions,
    batch_label="Parametric differentiation q036–q053",
)
print(f"Wrote {len(questions)} questions to {OUT}")
print(f"Intermediate: {intermediate}, Hard: {hard}")
for q in questions:
    print(f"  {q['id']}: {q['difficulty']}, {len(q['workedSolution']['steps'])} steps")