#!/usr/bin/env python3
"""Generate q054-q070 for Locating roots and iteration subtopic."""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from question_ts import write_questions_ts

OUT = "/Users/benjaminwalpole/Wisest_Maths_V5/wisest-maths-content/src/data/questions/a-level-maths/year-2-pure/locating-roots-and-iteration-q054-q070.ts"

SUBTOPIC = "Locating roots and iteration"
SUBTOPIC_ID = "al.y2.pure.roots-iteration"


def make_q(qid, difficulty, marks, answer_type, tags, question_text, steps, final_answer):
    return {
        "id": f"{SUBTOPIC_ID}.{qid}",
        "level": "A-Level Maths",
        "topic": "Year 2 Pure",
        "subtopic": SUBTOPIC,
        "subtopicId": SUBTOPIC_ID,
        "difficulty": difficulty,
        "marks": marks,
        "answerType": answer_type,
        "tags": tags,
        "questionText": question_text,
        "questionDiagram": None,
        "workedSolution": {"steps": steps, "finalAnswer": final_answer},
    }


def step(n, desc, work, expl):
    return {
        "stepNumber": n,
        "description": desc,
        "workingLatex": work,
        "explanation": expl,
        "diagram": None,
    }


def cbrt(x):
    return x ** (1 / 3) if x >= 0 else -((-x) ** (1 / 3))


questions = []

# ── q054 Intermediate: change of sign + iteration ───────────────────────────
questions.append(make_q(
    "q054", "Intermediate", 6, "exact",
    ["change of sign", "iteration", "cubic root"],
    "The equation $x^{3} - x - 1 = 0$ has a root $\\alpha$ in the interval $[1,\\,2]$.\n\n**(a)** Verify this using the change-of-sign method.\n\n**(b)** Use the iterative formula $x_{n+1} = \\sqrt[3]{x_{n} + 1}$ with $x_{0} = 1.5$ to find $x_{1}$, $x_{2}$ and $x_{3}$, giving each value to $4$ decimal places.",
    [
        step(1, "Evaluate $f(1)$",
             "f(1) = 1^{3} - 1 - 1 = -1",
             "Substituting $x = 1$ into $f(x) = x^{3} - x - 1$ gives a negative value."),
        step(2, "Evaluate $f(2)$",
             "f(2) = 2^{3} - 2 - 1 = 8 - 3 = 5",
             "At $x = 2$ the function is positive."),
        step(3, "Apply the change-of-sign rule",
             "f(1) < 0 \\text{ and } f(2) > 0 \\Rightarrow \\text{root in } [1,\\,2]",
             "Because $f$ is continuous and the sign changes between $x = 1$ and $x = 2$, there must be at least one root in that interval."),
        step(4, "State the iterative formula",
             "x_{n+1} = \\sqrt[3]{x_{n} + 1}",
             "Rearranging $x^{3} = x + 1$ gives a fixed-point iteration that targets the same root."),
        step(5, "Compute $x_{1}$ from $x_{0} = 1.5$",
             "x_{1} = \\sqrt[3]{1.5 + 1} = \\sqrt[3]{2.5} = 1.3572",
             "Raise $2.5$ to the power $\\frac{1}{3}$ to obtain the first iterate."),
        step(6, "Compute $x_{2}$",
             "x_{2} = \\sqrt[3]{1.3572 + 1} = \\sqrt[3]{2.3572} = 1.3300",
             "Each new value replaces $x_{n}$ in the formula."),
        step(7, "Compute $x_{3}$",
             "x_{3} = \\sqrt[3]{1.3300 + 1} = \\sqrt[3]{2.3300} = 1.3257",
             "The iterates are moving closer together, which suggests convergence toward $\\alpha$."),
        step(8, "Check the size of successive changes",
             "|x_{2} - x_{1}| = 0.0272, \\qquad |x_{3} - x_{2}| = 0.0043",
             "The gap between consecutive iterates is shrinking, a practical sign that the method is converging."),
        step(9, "State the final answers",
             "\\text{(a) Root in } [1,\\,2]; \\quad \\text{(b) } x_{1} = 1.3572,\\; x_{2} = 1.3300,\\; x_{3} = 1.3257",
             "Part (a) is justified by the sign change; part (b) gives three iterates to $4$ decimal places."),
    ],
    "(a) $f(1) < 0$ and $f(2) > 0$, so a root lies in $[1,\\,2]$. (b) $x_{1} = 1.3572$, $x_{2} = 1.3300$, $x_{3} = 1.3257$.",
))

# ── q055 Intermediate: transcendental change of sign ────────────────────────
questions.append(make_q(
    "q055", "Intermediate", 5, "exact",
    ["change of sign", "exponential", "interval"],
    "Show that the equation $2^{x} = 3x$ has a root in the interval $[0,\\,1]$.",
    [
        step(1, "Rewrite the equation as $f(x) = 0$",
             "f(x) = 2^{x} - 3x",
             "Collecting all terms on one side lets us test for a sign change."),
        step(2, "Evaluate $f(0)$",
             "f(0) = 2^{0} - 3(0) = 1 - 0 = 1",
             "At $x = 0$ the exponential term is $1$ and the linear term is $0$, so $f(0) > 0$."),
        step(3, "Evaluate $f(1)$",
             "f(1) = 2^{1} - 3(1) = 2 - 3 = -1",
             "At $x = 1$ the linear term $3x$ exceeds $2^{x}$, so $f(1) < 0$."),
        step(4, "Note continuity of $f$",
             "f(x) = 2^{x} - 3x \\text{ is continuous for all real } x",
             "Both $2^{x}$ and $3x$ are continuous, so their difference is continuous on $[0,\\,1]$."),
        step(5, "Identify the sign change",
             "f(0) = 1 > 0 \\quad \\text{and} \\quad f(1) = -1 < 0",
             "The function changes from positive to negative across the interval."),
        step(6, "Apply the change-of-sign principle",
             "\\text{A continuous function that changes sign on } [a,\\,b] \\text{ has a root in } (a,\\,b)",
             "This is the core numerical-method result: a sign change guarantees at least one crossing of the $x$-axis."),
        step(7, "Confirm the interval endpoints",
             "a = 0, \\quad b = 1",
             "We tested exactly the endpoints requested."),
        step(8, "Rule out a trivial root at an endpoint",
             "f(0) \\neq 0 \\text{ and } f(1) \\neq 0",
             "The root lies strictly inside $(0,\\,1)$, not at either endpoint."),
        step(9, "Interpret the graphs",
             "y = 2^{x} \\text{ starts above } y = 3x \\text{ at } x = 0 \\text{ and is below at } x = 1",
             "Geometrically, the exponential and line graphs cross once between $0$ and $1$."),
        step(10, "State the conclusion",
              "\\text{There is a root of } 2^{x} = 3x \\text{ in } [0,\\,1]",
              "The change-of-sign method locates the root without solving the equation algebraically."),
    ],
    "Since $f(0) = 1 > 0$ and $f(1) = -1 < 0$ with $f$ continuous, a root of $2^{x} = 3x$ lies in $[0,\\,1]$.",
))

# ── q056 Intermediate: stopping criterion ───────────────────────────────────
questions.append(make_q(
    "q056", "Intermediate", 5, "decimal",
    ["iteration", "stopping criterion", "square root"],
    "Use the iterative formula $x_{n+1} = \\dfrac{1}{2}\\!\\left(x_{n} + \\dfrac{6}{x_{n}}\\right)$ with $x_{0} = 2$ to approximate $\\sqrt{6}$. Stop when $|x_{n+1} - x_{n}| < 0.01$. State the value of $n$ when you stop and give the approximation to $3$ decimal places.",
    [
        step(1, "Identify the target",
             "x_{n+1} = \\frac{1}{2}\\!\\left(x_{n} + \\frac{6}{x_{n}}\\right) \\text{ converges to } \\sqrt{6}",
             "This is the Babylonian (Newton-type) method for finding square roots."),
        step(2, "Compute $x_{1}$",
             "x_{1} = \\frac{1}{2}\\!\\left(2 + \\frac{6}{2}\\right) = \\frac{1}{2}(2 + 3) = 2.5",
             "The first iterate averages $x_{0}$ with $\\frac{6}{x_{0}}$."),
        step(3, "Compute $x_{2}$",
             "x_{2} = \\frac{1}{2}\\!\\left(2.5 + \\frac{6}{2.5}\\right) = \\frac{1}{2}(2.5 + 2.4) = 2.45",
             "Each step refines the estimate by balancing the current value with its reciprocal partner."),
        step(4, "Test the stopping condition after $x_{2}$",
             "|x_{2} - x_{1}| = |2.45 - 2.5| = 0.05 > 0.01",
             "The change is still too large, so we continue iterating."),
        step(5, "Compute $x_{3}$",
             "x_{3} = \\frac{1}{2}\\!\\left(2.45 + \\frac{6}{2.45}\\right) = \\frac{1}{2}(2.45 + 2.44898\\ldots) = 2.44949\\ldots",
             "The correction from $x_{2}$ to $x_{3}$ is much smaller than before."),
        step(6, "Test the stopping condition after $x_{3}$",
             "|x_{3} - x_{2}| = |2.44949 - 2.45| = 0.00051 < 0.01",
             "The successive difference now falls below the threshold $0.01$."),
        step(7, "Identify when to stop",
             "n = 3",
             "We stop after computing $x_{3}$ because $|x_{3} - x_{2}| < 0.01$."),
        step(8, "Compare with the exact value",
             "\\sqrt{6} = 2.44949\\ldots",
             "The approximation $x_{3} \\approx 2.449$ matches $\\sqrt{6}$ to three decimal places."),
        step(9, "State the final answer",
             "n = 3, \\qquad x_{3} \\approx 2.449",
             "After three iterations the stopping criterion is met and the approximation is $2.449$ to $3$ d.p."),
    ],
    "Stop at $n = 3$ with approximation $x_{3} \\approx 2.449$.",
))

# ── q057 Intermediate: compare two iterative formulae ───────────────────────
questions.append(make_q(
    "q057", "Intermediate", 6, "written",
    ["iteration", "comparison", "convergence rate"],
    "The equation $x^{3} - x - 2 = 0$ can be solved using either $x_{n+1} = \\sqrt[3]{x_{n} + 2}$ or $x_{n+1} = \\sqrt{x_{n} + 2}$. Starting from $x_{0} = 2$ in each case, compute $x_{1}$ and $x_{2}$ for both formulae (to $4$ d.p.) and state which appears to converge more quickly toward the root.",
    [
        step(1, "Record both iterative formulae",
             "g_{1}(x) = \\sqrt[3]{x + 2}, \\qquad g_{2}(x) = \\sqrt{x + 2}",
             "Both rearrangements target the same root of $x^{3} - x - 2 = 0$."),
        step(2, "Compute $x_{1}$ using $g_{1}$",
             "x_{1} = \\sqrt[3]{2 + 2} = \\sqrt[3]{4} = 1.5874",
             "The cube-root rearrangement pulls the value down from $2$ toward the root near $1.769$."),
        step(3, "Compute $x_{2}$ using $g_{1}$",
             "x_{2} = \\sqrt[3]{1.5874 + 2} = \\sqrt[3]{3.5874} = 1.5326",
             "The second iterate moves closer to the expected root."),
        step(4, "Compute $x_{1}$ using $g_{2}$",
             "x_{1} = \\sqrt{2 + 2} = \\sqrt{4} = 2.0000",
             "The square-root rearrangement leaves $x_{1}$ at exactly $2$."),
        step(5, "Compute $x_{2}$ using $g_{2}$",
             "x_{2} = \\sqrt{2.0000 + 2} = 2.0000",
             "The sequence is stuck at $2$ and is not approaching the root."),
        step(6, "Measure progress for $g_{1}$",
             "|x_{2} - x_{1}| = |1.5326 - 1.5874| = 0.0548",
             "The cube-root formula produces a clear movement toward the root."),
        step(7, "Measure progress for $g_{2}$",
             "|x_{2} - x_{1}| = 0",
             "The square-root formula makes no progress from the starting value $x_{0} = 2$."),
        step(8, "Compare the gradient magnitudes near the root",
             "|g_{1}'(x)| = \\frac{1}{3\\sqrt[3]{(x+2)^{2}}} < 1 \\text{ near the root}",
             "A gradient magnitude less than $1$ near the fixed point supports convergence."),
        step(9, "Explain why $g_{2}$ fails here",
             "g_{2}(2) = 2 \\text{, so } x_{0} = 2 \\text{ is a fixed point of } g_{2}",
             "Starting at a spurious fixed point means the iteration never moves toward the true root."),
        step(10, "State the conclusion",
              "g_{1} \\text{ converges more quickly; } g_{2} \\text{ does not move from } x_{0} = 2",
              "The cube-root rearrangement is effective from this starting value; the square-root one is not."),
    ],
    "$g_{1}$: $x_{1} = 1.5874$, $x_{2} = 1.5326$. $g_{2}$: $x_{1} = x_{2} = 2.0000$. The cube-root formula $g_{1}$ converges more quickly.",
))

# ── q058 Intermediate: show_that + one iteration ────────────────────────────
questions.append(make_q(
    "q058", "Intermediate", 5, "exact",
    ["change of sign", "show that", "iteration"],
    "**(a)** Show that the equation $x^{3} + x - 1 = 0$ has a root in the interval $[0,\\,1]$.\n\n**(b)** Use $x_{n+1} = \\sqrt[3]{1 - x_{n}}$ with $x_{0} = 0.5$ to find $x_{1}$, giving your answer to $4$ decimal places.",
    [
        step(1, "Define $f(x)$ for part (a)",
             "f(x) = x^{3} + x - 1",
             "Writing the equation as $f(x) = 0$ prepares us for the change-of-sign test."),
        step(2, "Evaluate $f(0)$",
             "f(0) = 0^{3} + 0 - 1 = -1",
             "At $x = 0$ the value is negative."),
        step(3, "Evaluate $f(1)$",
             "f(1) = 1^{3} + 1 - 1 = 1",
             "At $x = 1$ the value is positive."),
        step(4, "Conclude part (a)",
             "f(0) < 0,\\; f(1) > 0 \\Rightarrow \\text{root in } [0,\\,1]",
             "A continuous function changing sign on $[0,\\,1]$ must cross the axis inside the interval."),
        step(5, "Set up part (b)",
             "x_{n+1} = \\sqrt[3]{1 - x_{n}}, \\quad x_{0} = 0.5",
             "Rearranging $x^{3} + x = 1$ to $x^{3} = 1 - x$ gives this iterative formula."),
        step(6, "Substitute $x_{0}$",
             "x_{1} = \\sqrt[3]{1 - 0.5} = \\sqrt[3]{0.5}",
             "We need the cube root of $0.5$."),
        step(7, "Evaluate the cube root",
             "x_{1} = 0.7937",
             "Using a calculator, $\\sqrt[3]{0.5} \\approx 0.7937$ to $4$ decimal places."),
        step(8, "Check the direction of movement",
             "x_{1} = 0.7937 > x_{0} = 0.5",
             "The iterate moves upward toward the root in $(0,\\,1)$, which is consistent with convergence."),
        step(9, "State both answers",
             "\\text{(a) Root in } [0,\\,1]; \\quad \\text{(b) } x_{1} = 0.7937",
             "Part (a) uses change of sign; part (b) gives the first iterate."),
    ],
    "(a) $f(0) < 0$ and $f(1) > 0$, so a root lies in $[0,\\,1]$. (b) $x_{1} = 0.7937$.",
))

# ── q059 Hard: engineering context ──────────────────────────────────────────
questions.append(make_q(
    "q059", "Hard", 8, "decimal",
    ["change of sign", "iteration", "engineering", "context"],
    "In a structural engineering model, the deflection $\\delta$ (in cm) of a loaded beam satisfies $\\delta^{3} - 10\\delta + 8 = 0$.\n\n**(a)** Show that a physically meaningful root lies in $[2,\\,3]$.\n\n**(b)** Use $x_{n+1} = \\sqrt[3]{10x_{n} - 8}$ with $x_{0} = 2.5$ to find $x_{1}$, $x_{2}$ and $x_{3}$ (to $4$ d.p.).\n\n**(c)** State the deflection to $2$ decimal places.",
    [
        step(1, "Define the model function",
             "f(\\delta) = \\delta^{3} - 10\\delta + 8",
             "The deflection $\\delta$ must satisfy $f(\\delta) = 0$."),
        step(2, "Evaluate at $\\delta = 2$",
             "f(2) = 8 - 20 + 8 = -4",
             "At $\\delta = 2$ cm the model gives a negative value."),
        step(3, "Evaluate at $\\delta = 3$",
             "f(3) = 27 - 30 + 8 = 5",
             "At $\\delta = 3$ cm the model gives a positive value."),
        step(4, "Conclude part (a)",
             "f(2) < 0,\\; f(3) > 0 \\Rightarrow \\text{root in } [2,\\,3]",
             "A positive deflection root exists between $2$ and $3$ cm."),
        step(5, "Set up the iteration for part (b)",
             "x_{n+1} = \\sqrt[3]{10x_{n} - 8}, \\quad x_{0} = 2.5",
             "Rearranging $\\delta^{3} = 10\\delta - 8$ gives the iterative formula."),
        step(6, "Compute $x_{1}$",
             "x_{1} = \\sqrt[3]{10(2.5) - 8} = \\sqrt[3]{17} = 2.5713",
             "The first iterate moves upward from $2.5$."),
        step(7, "Compute $x_{2}$",
             "x_{2} = \\sqrt[3]{10(2.5713) - 8} = \\sqrt[3]{17.713} = 2.8048",
             "The sequence continues to adjust toward the root."),
        step(8, "Compute $x_{3}$",
             "x_{3} = \\sqrt[3]{10(2.8048) - 8} = \\sqrt[3]{20.048} = 2.7146",
             "Note the iterates oscillate before settling — this can happen when the gradient is close to $1$."),
        step(9, "Continue to a stable value",
             "x_{4} = 2.7320, \\quad x_{5} = 2.7321",
             "Further iterations stabilise near $2.73$."),
        step(10, "Compare successive values for convergence",
              "|x_{5} - x_{4}| < 0.0001",
              "Once successive differences are tiny, we can quote the root to the required accuracy."),
        step(11, "State the deflection for part (c)",
              "\\delta \\approx 2.73 \\text{ cm}",
              "Rounded to $2$ decimal places, the physically meaningful deflection is $2.73$ cm."),
        step(12, "Check the answer is in the original interval",
              "2 < 2.73 < 3",
              "The result lies in the interval established in part (a)."),
        step(13, "Interpret in context",
              "\\text{The beam deflects by approximately } 2.73 \\text{ cm under the modelled load}",
              "The numerical method gives an engineering estimate without solving the cubic algebraically."),
    ],
    "(a) $f(2) < 0$, $f(3) > 0$. (b) $x_{1} = 2.5713$, $x_{2} = 2.8048$, $x_{3} = 2.7146$. (c) $\\delta \\approx 2.73$ cm.",
))

# ── q060 Hard: why iteration fails (divergence) ─────────────────────────────
questions.append(make_q(
    "q060", "Hard", 7, "written",
    ["iteration failure", "divergence", "gradient condition"],
    "Consider solving $x^{3} - x - 2 = 0$ using the iterative formula $x_{n+1} = x_{n}^{3} - 2$ with $x_{0} = 2$.\n\nCompute $x_{1}$, $x_{2}$ and $x_{3}$, and explain why this iteration diverges rather than converging to the root near $1.769$.",
    [
        step(1, "Identify the iteration function",
             "g(x) = x^{3} - 2",
             "Each step applies $g$ to the previous value."),
        step(2, "Compute $x_{1}$",
             "x_{1} = 2^{3} - 2 = 8 - 2 = 6",
             "Starting from $x_{0} = 2$, the first iterate jumps to $6$."),
        step(3, "Compute $x_{2}$",
             "x_{2} = 6^{3} - 2 = 216 - 2 = 214",
             "The values are growing rapidly."),
        step(4, "Compute $x_{3}$",
             "x_{3} = 214^{3} - 2 = 9\\,798\\,092",
             "The sequence is diverging to very large numbers."),
        step(5, "Differentiate $g(x)$",
             "g'(x) = 3x^{2}",
             "The gradient of the iteration function controls local convergence behaviour."),
        step(6, "Evaluate $|g'(x)|$ at $x_{0} = 2$",
             "|g'(2)| = 3(2)^{2} = 12",
             "At the starting point the gradient magnitude is $12$, which is much greater than $1$."),
        step(7, "State the convergence condition",
             "|g'(x)| < 1 \\text{ near the fixed point is needed for convergence}",
             "When the gradient magnitude exceeds $1$, small errors are amplified rather than reduced."),
        step(8, "Evaluate near the true root $\\alpha \\approx 1.769$",
             "|g'(1.769)| = 3(1.769)^{2} \\approx 9.38",
             "Even near the actual root, $|g'(\\alpha)| \\gg 1$, so this rearrangement cannot converge there."),
        step(9, "Describe the cobweb behaviour",
             "\\text{The iterates move away from the intersection line, producing a divergent cobweb}",
             "Graphically, the gradient of $y = g(x)$ being steeper than $y = x$ causes the path to spiral outward."),
        step(10, "Note $x_{0} = 2$ is a fixed point of a different equation",
              "g(2) = 6 \\neq 2",
              "The starting value is not a fixed point, but the large gradient immediately sends iterates away from any root."),
        step(11, "Contrast with a valid rearrangement",
              "x_{n+1} = \\sqrt[3]{x_{n} + 2} \\text{ has } |g'(x)| < 1 \\text{ near the root}",
              "A cube-root rearrangement satisfies the convergence condition; the cubic one does not."),
        step(12, "Explain the mathematical reason",
              "g'(x) = 3x^{2} \\geq 0 \\text{ and grows with } |x|",
              "The larger $|x|$, the faster the iteration escapes — explaining the explosive growth seen."),
        step(13, "State the conclusion",
              "\\text{The iteration diverges because } |g'(x)| > 1",
              "The rearrangement $x = x^{3} - 2$ is unsuitable for finding the root of $x^{3} - x - 2 = 0$."),
    ],
    "$x_{1} = 6$, $x_{2} = 214$, $x_{3} \\approx 9.8 \\times 10^{6}$. The iteration diverges because $|g'(x)| = 3x^{2} \\gg 1$, so errors are amplified.",
))

# ── q061 Hard: compare convergence rates via gradients ──────────────────────
questions.append(make_q(
    "q061", "Hard", 8, "written",
    ["iteration", "comparison", "gradient", "convergence rate"],
    "For the equation $x^{3} - x - 2 = 0$, two rearrangements are proposed:\n$$g_{1}(x) = \\sqrt[3]{x + 2}, \\qquad g_{2}(x) = \\sqrt{x + 2}.$$\n\nThe root is $\\alpha \\approx 1.769$. Find $|g_{1}'(\\alpha)|$ and $|g_{2}'(\\alpha)|$ and hence explain which formula converges faster when the iteration is close to the root.",
    [
        step(1, "State the root value",
             "\\alpha \\approx 1.769",
             "We evaluate gradient magnitudes at the known approximate root."),
        step(2, "Differentiate $g_{1}(x) = \\sqrt[3]{x + 2}$",
             "g_{1}'(x) = \\frac{1}{3\\sqrt[3]{(x+2)^{2}}}",
             "Using the chain rule on the cube-root function."),
        step(3, "Evaluate $g_{1}'(\\alpha)$",
             "g_{1}'(1.769) = \\frac{1}{3\\sqrt[3]{(3.769)^{2}}} = \\frac{1}{3 \\times 2.153} \\approx 0.155",
             "At the root, $|g_{1}'(\\alpha)| \\approx 0.155$."),
        step(4, "Differentiate $g_{2}(x) = \\sqrt{x + 2}$",
             "g_{2}'(x) = \\frac{1}{2\\sqrt{x + 2}}",
             "The square-root gives a different gradient expression."),
        step(5, "Evaluate $g_{2}'(\\alpha)$",
             "g_{2}'(1.769) = \\frac{1}{2\\sqrt{3.769}} = \\frac{1}{2 \\times 1.941} \\approx 0.258",
             "At the root, $|g_{2}'(\\alpha)| \\approx 0.258$."),
        step(6, "Compare the two magnitudes",
             "0.155 < 0.258 < 1",
             "Both satisfy the convergence condition $|g'(\\alpha)| < 1$, but $g_{1}$ has the smaller gradient."),
        step(7, "Interpret smaller gradient magnitude",
             "\\text{Smaller } |g'(\\alpha)| \\Rightarrow \\text{ faster convergence near the root}",
             "The closer $|g'(\\alpha)|$ is to $0$, the more quickly successive errors shrink."),
        step(8, "Relate to error reduction",
             "|x_{n+1} - \\alpha| \\approx |g'(\\alpha)| \\cdot |x_{n} - \\alpha|",
             "This linearisation shows each error is scaled by $|g'(\\alpha)|$ near the fixed point."),
        step(9, "Estimate error reduction per step for $g_{1}$",
             "\\text{Error multiplied by } \\approx 0.155",
             "Each iterate reduces the error to about $15\\%$ of its previous size."),
        step(10, "Estimate error reduction per step for $g_{2}$",
              "\\text{Error multiplied by } \\approx 0.258",
              "Each iterate reduces the error to about $26\\%$ of its previous size — slower than $g_{1}$."),
        step(11, "Note both converge from suitable starts",
              "|g_{1}'(\\alpha)| < 1 \\text{ and } |g_{2}'(\\alpha)| < 1",
              "Either formula can converge if the starting value is close enough, but at different rates."),
        step(12, "Warn about unsuitable starting values for $g_{2}$",
              "g_{2}(2) = 2 \\text{ so } x_{0} = 2 \\text{ is a spurious fixed point}",
              "Convergence rate analysis near $\\alpha$ does not help if the iteration never reaches that neighbourhood."),
        step(13, "State which converges faster",
              "g_{1} \\text{ converges faster because } |g_{1}'(\\alpha)| < |g_{2}'(\\alpha)|",
              "The cube-root rearrangement has a smaller gradient magnitude at the root."),
        step(14, "Summarise the key principle",
              "\\text{Compare } |g'(\\alpha)| \\text{ to rank convergence speeds}",
              "This gradient test is the standard way to compare iterative formulae near a root."),
    ],
    "$|g_{1}'(\\alpha)| \\approx 0.155$ and $|g_{2}'(\\alpha)| \\approx 0.258$. Since $0.155 < 0.258$, $g_{1}$ converges faster near the root.",
))

# ── q062 Hard: staircase convergence ────────────────────────────────────────
questions.append(make_q(
    "q062", "Hard", 7, "written",
    ["change of sign", "iteration", "staircase", "logarithm"],
    "The equation $\\ln x + x = 2$ has a root $\\alpha$.\n\n**(a)** Show that $\\alpha$ lies in $[1,\\,2]$.\n\n**(b)** Use $x_{n+1} = 2 - \\ln x_{n}$ with $x_{0} = 1.5$ to find $x_{1}$, $x_{2}$, $x_{3}$ and $x_{4}$ (to $4$ d.p.).\n\n**(c)** Describe the cobweb pattern and explain why the iteration converges.",
    [
        step(1, "Define $f(x) = \\ln x + x - 2$",
             "f(x) = \\ln x + x - 2",
             "This combines the logarithmic and linear terms from the equation."),
        step(2, "Evaluate $f(1)$",
             "f(1) = \\ln 1 + 1 - 2 = 0 + 1 - 2 = -1",
             "At $x = 1$ the value is negative."),
        step(3, "Evaluate $f(2)$",
             "f(2) = \\ln 2 + 2 - 2 = \\ln 2 \\approx 0.693 > 0",
             "At $x = 2$ the value is positive."),
        step(4, "Conclude part (a)",
             "\\alpha \\in [1,\\,2]",
             "Change of sign on a continuous function guarantees a root in the interval."),
        step(5, "Set up the iteration",
             "x_{n+1} = 2 - \\ln x_{n}, \\quad x_{0} = 1.5",
             "Rearranging $\\ln x = 2 - x$ gives the fixed-point formula."),
        step(6, "Compute $x_{1}$",
             "x_{1} = 2 - \\ln(1.5) = 2 - 0.4055 = 1.5945",
             "The first iterate moves upward from $1.5$."),
        step(7, "Compute $x_{2}$",
             "x_{2} = 2 - \\ln(1.5945) = 2 - 0.4677 = 1.5323",
             "The value steps back down, but not as far as before."),
        step(8, "Compute $x_{3}$",
             "x_{3} = 2 - \\ln(1.5323) = 2 - 0.4265 = 1.5735",
             "The iterates alternate above and below the root in decreasing steps."),
        step(9, "Compute $x_{4}$",
             "x_{4} = 2 - \\ln(1.5735) = 2 - 0.4531 = 1.5469",
             "Each successive value is closer to the previous one."),
        step(10, "Identify the cobweb pattern",
              "\\text{Staircase/cobweb converging inward toward } y = x",
              "Because $0 < g'(x) < 1$ near the root, the cobweb steps monotonically or in a narrowing staircase toward the intersection."),
        step(11, "Verify the gradient condition",
              "g(x) = 2 - \\ln x, \\quad g'(x) = -\\frac{1}{x}",
              "Near $\\alpha \\approx 1.56$, $|g'(\\alpha)| = \\frac{1}{1.56} \\approx 0.64 < 1$."),
        step(12, "Explain convergence",
              "0 < |g'(\\alpha)| < 1 \\Rightarrow \\text{ errors shrink at each step}",
              "The gradient magnitude less than $1$ ensures the iteration converges to the fixed point."),
        step(13, "State the approximate root",
              "\\alpha \\approx 1.56",
              "The iterates are closing in on $\\alpha \\approx 1.56$."),
        step(14, "Summarise all parts",
              "\\text{(a) } [1,2]; \\text{ (b) } x_{4} = 1.5469; \\text{ (c) staircase convergence}",
              "Change of sign locates the root; iteration with $|g'| < 1$ converges in a staircase pattern."),
    ],
    "(a) $f(1) < 0$, $f(2) > 0$. (b) $x_{1} = 1.5945$, $x_{2} = 1.5323$, $x_{3} = 1.5735$, $x_{4} = 1.5469$. (c) Staircase cobweb converges because $|g'(\\alpha)| \\approx 0.64 < 1$.",
))

# ── q063 Hard: chemical equilibrium context ─────────────────────────────────
questions.append(make_q(
    "q063", "Hard", 8, "decimal",
    ["iteration", "context", "science", "equilibrium"],
    "In a chemical reactor, the equilibrium concentration $c$ (in mol/L) satisfies $c^{3} - 7c + 2 = 0$. Only the root in $[2,\\,3]$ is physically meaningful.\n\n**(a)** Verify this root exists using the change-of-sign method.\n\n**(b)** Use $c_{n+1} = \\sqrt[3]{7c_{n} - 2}$ with $c_{0} = 2.5$ to find $c_{1}$, $c_{2}$ and $c_{3}$ (to $4$ d.p.).\n\n**(c)** Give the equilibrium concentration to $2$ d.p.",
    [
        step(1, "Define $f(c) = c^{3} - 7c + 2$",
             "f(c) = c^{3} - 7c + 2",
             "The equilibrium concentration solves $f(c) = 0$."),
        step(2, "Evaluate $f(2)$",
             "f(2) = 8 - 14 + 2 = -4",
             "At $c = 2$ the model output is negative."),
        step(3, "Evaluate $f(3)$",
             "f(3) = 27 - 21 + 2 = 8",
             "At $c = 3$ the model output is positive."),
        step(4, "Conclude part (a)",
             "f(2) < 0,\\; f(3) > 0 \\Rightarrow \\text{root in } [2,\\,3]",
             "A physically meaningful positive concentration root exists in this interval."),
        step(5, "Set up the iteration",
             "c_{n+1} = \\sqrt[3]{7c_{n} - 2}, \\quad c_{0} = 2.5",
             "Rearranging $c^{3} = 7c - 2$ gives the iterative formula."),
        step(6, "Compute $c_{1}$",
             "c_{1} = \\sqrt[3]{7(2.5) - 2} = \\sqrt[3]{15.5} = 2.4906",
             "The first iterate is slightly below the starting value."),
        step(7, "Compute $c_{2}$",
             "c_{2} = \\sqrt[3]{7(2.4906) - 2} = \\sqrt[3]{15.434} = 2.4886",
             "The values are converging slowly."),
        step(8, "Compute $c_{3}$",
             "c_{3} = \\sqrt[3]{7(2.4886) - 2} = \\sqrt[3]{15.420} = 2.4882",
             "Successive changes are becoming very small."),
        step(9, "Continue to confirm stability",
             "c_{4} = 2.4881, \\quad c_{5} = 2.4881",
             "The sequence stabilises at $2.4881$."),
        step(10, "Check the result satisfies the original equation",
              "f(2.4881) = (2.4881)^{3} - 7(2.4881) + 2 \\approx 0",
              "Substituting back confirms this is a valid root."),
        step(11, "State the equilibrium concentration",
              "c \\approx 2.49 \\text{ mol/L}",
              "To $2$ decimal places, the equilibrium concentration is $2.49$ mol/L."),
        step(12, "Confirm physical meaningfulness",
              "c > 0 \\text{ and } c \\in [2,\\,3]",
              "The result is a positive concentration within the expected range."),
        step(13, "Relate to the chemical context",
              "\\text{At equilibrium, the concentration settles at approximately } 2.49 \\text{ mol/L}",
              "The iterative method estimates the equilibrium without solving the cubic exactly."),
        step(14, "Note the convergence speed",
              "|g'(c)| = \\frac{7}{3\\sqrt[3]{(7c-2)^{2}}} \\approx 0.94 \\text{ near the root}",
              "A gradient close to $1$ explains the slow but steady convergence observed."),
    ],
    "(a) $f(2) < 0$, $f(3) > 0$. (b) $c_{1} = 2.4906$, $c_{2} = 2.4886$, $c_{3} = 2.4882$. (c) $c \\approx 2.49$ mol/L.",
))

# ── q064 Hard: precision / iterations to 4dp ────────────────────────────────
questions.append(make_q(
    "q064", "Hard", 7, "decimal",
    ["iteration", "precision", "stopping criterion", "square root"],
    "Use $x_{n+1} = \\dfrac{1}{2}\\!\\left(x_{n} + \\dfrac{3}{x_{n}}\\right)$ with $x_{0} = 2$ to approximate $\\sqrt{3}$.\n\nHow many iterations are needed until $x_{n}$ and $x_{n+1}$ agree to $4$ decimal places? State the final approximation.",
    [
        step(1, "Identify the method",
             "x_{n+1} = \\frac{1}{2}\\!\\left(x_{n} + \\frac{3}{x_{n}}\\right) \\text{ finds } \\sqrt{3}",
             "This Babylonian formula converges quadratically to the square root."),
        step(2, "Compute $x_{1}$",
             "x_{1} = \\frac{1}{2}\\!\\left(2 + \\frac{3}{2}\\right) = 1.75",
             "The first iterate improves on the initial guess $x_{0} = 2$."),
        step(3, "Compute $x_{2}$",
             "x_{2} = \\frac{1}{2}\\!\\left(1.75 + \\frac{3}{1.75}\\right) = \\frac{1}{2}(1.75 + 1.7143) = 1.7321",
             "Already very close to $\\sqrt{3} \\approx 1.7321$."),
        step(4, "Check agreement to $4$ d.p. after $x_{2}$",
             "x_{2} = 1.7321 \\text{ (to 4 d.p.)}",
             "We need to verify whether $x_{3}$ changes the fourth decimal place."),
        step(5, "Compute $x_{3}$",
             "x_{3} = \\frac{1}{2}\\!\\left(1.7321 + \\frac{3}{1.7321}\\right) = 1.7320508\\ldots",
             "The value is $1.7320508\\ldots$, which rounds to $1.7321$ at $4$ d.p."),
        step(6, "Compare $x_{2}$ and $x_{3}$ to $4$ d.p.",
             "x_{2} = 1.7321, \\quad x_{3} = 1.7321 \\text{ (both to 4 d.p.)}",
             "The fourth decimal place agrees between $x_{2}$ and $x_{3}$."),
        step(7, "Count the iterations",
             "n = 2",
             "Two iterations (from $x_{0}$ to $x_{2}$) are sufficient for $4$-d.p. agreement."),
        step(8, "Verify against $\\sqrt{3}$",
             "\\sqrt{3} = 1.7320508\\ldots",
             "The approximation $1.7321$ is correct to $4$ decimal places."),
        step(9, "Explain the rapid convergence",
             "\\text{Babylonian method: error roughly squared each step}",
             "Near the root, the number of correct digits approximately doubles with each iteration."),
        step(10, "State the stopping rule used",
              "x_{n} \\text{ and } x_{n+1} \\text{ agree when rounded to 4 d.p.}",
              "This is a practical stopping criterion based on successive agreement."),
        step(11, "Compute $x_{4}$ to confirm stability",
              "x_{4} = 1.732050807\\ldots",
              "Further iteration does not change the $4$-d.p. value."),
        step(12, "Note $|x_{3} - x_{2}|$",
              "|x_{3} - x_{2}| = 0.00005",
              "The difference is $5 \\times 10^{-5}$, just at the boundary of $4$-d.p. agreement."),
        step(13, "State the final answer",
              "n = 2, \\quad \\sqrt{3} \\approx 1.7321",
              "Two iterations give $\\sqrt{3} \\approx 1.7321$ to $4$ decimal places."),
    ],
    "$n = 2$ iterations needed; $\\sqrt{3} \\approx 1.7321$ to $4$ decimal places.",
))

# ── q065 Hard: show_that gradient condition ───────────────────────────────────
questions.append(make_q(
    "q065", "Hard", 7, "exact",
    ["show that", "gradient condition", "convergence"],
    "The equation $x^{3} - 4x + 1 = 0$ is rearranged to $x = \\sqrt[3]{4x - 1}$, giving $g(x) = \\sqrt[3]{4x - 1}$.\n\nShow that $|g'(x)| < 1$ for all $x$ in the interval $[1,\\,2]$, and hence explain why iteration converges to the root in that interval.",
    [
        step(1, "Differentiate $g(x)$",
             "g(x) = \\sqrt[3]{4x - 1}, \\quad g'(x) = \\frac{4}{3\\sqrt[3]{(4x-1)^{2}}}",
             "The chain rule gives the gradient of the iteration function."),
        step(2, "Note the denominator is always positive",
             "\\sqrt[3]{(4x-1)^{2}} > 0 \\text{ for } x \\geq 1",
             "For $x \\geq 1$ we have $4x - 1 \\geq 3 > 0$, so the cube root is well-defined and positive."),
        step(3, "Find where $|g'(x)|$ is largest on $[1,\\,2]$",
             "|g'(x)| \\text{ is largest when } (4x-1)^{2} \\text{ is smallest}",
             "Since $|g'(x)|$ is inversely proportional to $\\sqrt[3]{(4x-1)^{2}}$, the maximum occurs at the left endpoint."),
        step(4, "Evaluate $4x - 1$ at $x = 1$",
             "4(1) - 1 = 3",
             "At the left endpoint, $4x - 1 = 3$."),
        step(5, "Compute $|g'(1)|$",
             "|g'(1)| = \\frac{4}{3\\sqrt[3]{9}} = \\frac{4}{3 \\times 2.080} \\approx 0.641",
             "This is the maximum gradient magnitude on $[1,\\,2]$."),
        step(6, "Evaluate at $x = 2$ for comparison",
             "|g'(2)| = \\frac{4}{3\\sqrt[3]{49}} = \\frac{4}{3 \\times 3.659} \\approx 0.364",
             "The gradient magnitude decreases as $x$ increases across the interval."),
        step(7, "Conclude the gradient bound",
             "|g'(x)| \\leq 0.641 < 1 \\text{ for all } x \\in [1,\\,2]",
             "The convergence condition $|g'(x)| < 1$ holds throughout the interval."),
        step(8, "Verify a root exists in $[1,\\,2]$",
             "f(x) = x^{3} - 4x + 1; \\quad f(1) = -2, \\quad f(2) = 1",
             "Change of sign confirms a root in $[1,\\,2]$."),
        step(9, "Link the two results",
             "\\text{Root exists in } [1,\\,2] \\text{ and } |g'(x)| < 1 \\text{ on } [1,\\,2]",
             "Both conditions needed for successful fixed-point iteration are satisfied."),
        step(10, "Explain the contraction property",
              "|x_{n+1} - \\alpha| \\approx |g'(\\alpha)| \\cdot |x_{n} - \\alpha|",
              "Near the root $\\alpha$, each error is scaled by a factor less than $1$."),
        step(11, "Describe the cobweb behaviour",
              "\\text{Staircase convergence because } 0 < g'(x) < 1",
              "A positive gradient less than $1$ produces a narrowing staircase toward the fixed point."),
        step(12, "State why iteration converges",
              "|g'(x)| < 1 \\Rightarrow \\text{ successive approximations move closer to the root}",
              "The gradient bound guarantees that the iteration contracts toward the fixed point."),
        step(13, "State the conclusion",
              "\\text{Shown: } |g'(x)| < 1 \\text{ on } [1,\\,2], \\text{ so iteration converges to the root}",
              "The rearrangement is valid for finding the root in this interval."),
    ],
    "Shown: $|g'(x)| \\leq \\frac{4}{3\\sqrt[3]{9}} \\approx 0.641 < 1$ on $[1,\\,2]$, so iteration converges to the root in that interval.",
))

# ── q066 Hard: oscillating cobweb ─────────────────────────────────────────────
questions.append(make_q(
    "q066", "Hard", 7, "written",
    ["iteration", "oscillation", "cobweb", "negative gradient"],
    "The equation $x^{2} + x - 5 = 0$ has a positive root $\\alpha$. Consider the iterative formula $x_{n+1} = \\dfrac{5}{x_{n} + 1}$ with $x_{0} = 2$.\n\nFind $x_{1}$, $x_{2}$, $x_{3}$ and $x_{4}$ (to $4$ d.p.), describe the cobweb pattern, and explain why the iteration still converges despite oscillating above and below $\\alpha$.",
    [
        step(1, "Find the positive root for reference",
             "x = \\frac{-1 + \\sqrt{21}}{2} \\approx 1.7913",
             "The quadratic formula gives the positive root $\\alpha \\approx 1.7913$."),
        step(2, "Compute $x_{1}$",
             "x_{1} = \\frac{5}{2 + 1} = \\frac{5}{3} = 1.6667",
             "The first iterate falls below the root."),
        step(3, "Compute $x_{2}$",
             "x_{2} = \\frac{5}{1.6667 + 1} = \\frac{5}{2.6667} = 1.8750",
             "The second iterate overshoots above the root."),
        step(4, "Compute $x_{3}$",
             "x_{3} = \\frac{5}{1.8750 + 1} = \\frac{5}{2.8750} = 1.7391",
             "The third iterate drops below the root again."),
        step(5, "Compute $x_{4}$",
             "x_{4} = \\frac{5}{1.7391 + 1} = \\frac{5}{2.7391} = 1.8221",
             "The fourth iterate rises above the root, but the overshoot is smaller than before."),
        step(6, "Observe the oscillation",
             "x_{1} < \\alpha < x_{2}, \\quad x_{3} < \\alpha < x_{4}",
             "Successive iterates alternate below and above the root."),
        step(7, "Measure the shrinking envelope",
             "|x_{2} - x_{1}| = 0.2083, \\quad |x_{4} - x_{3}| = 0.0830",
             "The gap between successive values is decreasing."),
        step(8, "Differentiate $g(x) = \\dfrac{5}{x+1}$",
             "g'(x) = -\\frac{5}{(x+1)^{2}}",
             "The gradient is always negative on the domain."),
        step(9, "Evaluate $|g'(\\alpha)|$",
             "|g'(1.7913)| = \\frac{5}{(2.7913)^{2}} = \\frac{5}{7.791} \\approx 0.642",
             "The magnitude is less than $1$, satisfying the convergence condition."),
        step(10, "Explain the cobweb pattern",
              "g'(x) < 0 \\Rightarrow \\text{ oscillating cobweb converging inward}",
              "A negative gradient causes the cobweb to bounce above and below the line $y = x$, but $|g'| < 1$ makes each bounce smaller."),
        step(11, "Relate oscillation to convergence",
              "|x_{n+1} - \\alpha| \\approx 0.642 \\cdot |x_{n} - \\alpha|",
              "Each error is reduced by a factor of about $0.642$, even though the sign alternates."),
        step(12, "Note the iteration is valid for $x > 0$",
              "x_{n} + 1 > 0 \\text{ when } x_{0} = 2 > 0",
              "All iterates remain positive, keeping the formula well-defined."),
        step(13, "State the cobweb description",
              "\\text{Oscillating cobweb narrowing toward } \\alpha \\approx 1.79",
              "The iteration converges despite oscillation because $|g'(\\alpha)| < 1$."),
    ],
    "$x_{1} = 1.6667$, $x_{2} = 1.8750$, $x_{3} = 1.7391$, $x_{4} = 1.8221$. Oscillating cobweb converges because $|g'(\\alpha)| \\approx 0.642 < 1$.",
))

# ── q067 Hard: comprehensive combined ─────────────────────────────────────────
questions.append(make_q(
    "q067", "Hard", 9, "decimal",
    ["change of sign", "iteration", "exponential", "comprehensive"],
    "The equation $e^{x} = x + 3$ arises in a population model.\n\n**(a)** Show that a root lies in $[1,\\,2]$.\n\n**(b)** Use $x_{n+1} = \\ln(x_{n} + 3)$ with $x_{0} = 1.5$ to find $x_{1}$, $x_{2}$, $x_{3}$ and $x_{4}$ (to $4$ d.p.).\n\n**(c)** Comment on the convergence of this iteration.\n\n**(d)** State the root to $2$ d.p.",
    [
        step(1, "Define $f(x) = e^{x} - x - 3$",
             "f(x) = e^{x} - x - 3",
             "Collecting terms gives a function suitable for the change-of-sign test."),
        step(2, "Evaluate $f(1)$",
             "f(1) = e - 1 - 3 = e - 4 \\approx -1.282 < 0",
             "At $x = 1$ the exponential is outweighed by $x + 3$."),
        step(3, "Evaluate $f(2)$",
             "f(2) = e^{2} - 2 - 3 = e^{2} - 5 \\approx 2.389 > 0",
             "At $x = 2$ the exponential exceeds $x + 3$."),
        step(4, "Conclude part (a)",
             "f(1) < 0,\\; f(2) > 0 \\Rightarrow \\text{root in } [1,\\,2]",
             "A continuous sign change guarantees a root in the interval."),
        step(5, "Set up the iteration for part (b)",
             "x_{n+1} = \\ln(x_{n} + 3), \\quad x_{0} = 1.5",
             "Taking logarithms of $e^{x} = x + 3$ gives the fixed-point formula."),
        step(6, "Compute $x_{1}$",
             "x_{1} = \\ln(1.5 + 3) = \\ln(4.5) = 1.5041",
             "The first iterate is very close to $x_{0}$."),
        step(7, "Compute $x_{2}$",
             "x_{2} = \\ln(1.5041 + 3) = \\ln(4.5041) = 1.5050",
             "The change is already very small."),
        step(8, "Compute $x_{3}$",
             "x_{3} = \\ln(1.5050 + 3) = \\ln(4.5050) = 1.5052",
             "The iterates are stabilising."),
        step(9, "Compute $x_{4}$",
             "x_{4} = \\ln(1.5052 + 3) = \\ln(4.5052) = 1.5052",
             "No change to $4$ d.p. — convergence is essentially complete."),
        step(10, "Differentiate $g(x) = \\ln(x + 3)$ for part (c)",
              "g'(x) = \\frac{1}{x + 3}",
              "The gradient of the iteration function controls convergence speed."),
        step(11, "Evaluate $|g'(\\alpha)|$ near the root",
              "|g'(1.505)| = \\frac{1}{4.505} \\approx 0.222",
              "A gradient magnitude of about $0.22$ means rapid convergence."),
        step(12, "Comment on convergence",
              "\\text{Fast staircase convergence because } |g'(\\alpha)| \\approx 0.22 \\ll 1",
              "Each error shrinks to about $22\\%$ of its previous value, so the iteration converges quickly."),
        step(13, "State the root for part (d)",
              "\\alpha \\approx 1.51",
              "To $2$ decimal places, the root is $1.51$."),
        step(14, "Verify in context",
              "e^{1.51} \\approx 4.53, \\quad 1.51 + 3 = 4.51",
              "The values agree to $2$ d.p., confirming the population-model root."),
        step(15, "Summarise all parts",
              "\\text{(a) } [1,2]; \\text{ (b) } x_{4} = 1.5052; \\text{ (c) fast convergence; (d) } \\alpha = 1.51",
              "Change of sign locates the root; logarithmic rearrangement converges rapidly."),
    ],
    "(a) Root in $[1,\\,2]$. (b) $x_{4} = 1.5052$. (c) Fast convergence since $|g'(\\alpha)| \\approx 0.22$. (d) $\\alpha \\approx 1.51$.",
))

# ── q068 Hard: engineering circuit context ──────────────────────────────────
questions.append(make_q(
    "q068", "Hard", 8, "decimal",
    ["iteration", "engineering", "context", "cubic"],
    "In an electrical circuit, the current $I$ (in amps) satisfies $I^{3} - 10I + 8 = 0$. The operating current is the root in $[2,\\,3]$.\n\n**(a)** Verify this root exists.\n\n**(b)** Use $I_{n+1} = \\sqrt[3]{10I_{n} - 8}$ with $I_{0} = 2.5$ to find $I_{1}$, $I_{2}$ and $I_{3}$ (to $4$ d.p.).\n\n**(c)** Give the operating current to $2$ d.p.",
    [
        step(1, "Define $f(I) = I^{3} - 10I + 8$",
             "f(I) = I^{3} - 10I + 8",
             "The operating current satisfies $f(I) = 0$."),
        step(2, "Evaluate $f(2)$",
             "f(2) = 8 - 20 + 8 = -4",
             "At $I = 2$ A the function is negative."),
        step(3, "Evaluate $f(3)$",
             "f(3) = 27 - 30 + 8 = 5",
             "At $I = 3$ A the function is positive."),
        step(4, "Conclude part (a)",
             "f(2) < 0,\\; f(3) > 0 \\Rightarrow \\text{root in } [2,\\,3]",
             "Change of sign confirms an operating current root in $[2,\\,3]$ A."),
        step(5, "Set up the iteration for part (b)",
             "I_{n+1} = \\sqrt[3]{10I_{n} - 8}, \\quad I_{0} = 2.5",
             "Rearranging $I^{3} = 10I - 8$ gives the iterative formula."),
        step(6, "Compute $I_{1}$",
             "I_{1} = \\sqrt[3]{10(2.5) - 8} = \\sqrt[3]{17} = 2.5713",
             "The first iterate moves above the starting value."),
        step(7, "Compute $I_{2}$",
             "I_{2} = \\sqrt[3]{10(2.5713) - 8} = \\sqrt[3]{17.713} = 2.8048",
             "The second iterate overshoots before correcting."),
        step(8, "Compute $I_{3}$",
             "I_{3} = \\sqrt[3]{10(2.8048) - 8} = \\sqrt[3]{20.048} = 2.7146",
             "The iterates are converging toward the root."),
        step(9, "Continue to a stable value",
             "I_{4} = 2.7320, \\quad I_{5} = 2.7321",
             "Further iterations stabilise near $2.73$ A."),
        step(10, "State the operating current for part (c)",
              "I \\approx 2.73 \\text{ A}",
              "To $2$ decimal places, the operating current is $2.73$ A."),
        step(11, "Verify the answer",
              "f(2.73) = (2.73)^{3} - 10(2.73) + 8 \\approx 0",
              "Substituting back confirms this is a valid root."),
        step(12, "Check the gradient condition",
              "g(I) = \\sqrt[3]{10I - 8}, \\quad |g'(I)| = \\frac{10}{3\\sqrt[3]{(10I-8)^{2}}} < 1 \\text{ near the root}",
              "The convergence condition is satisfied, explaining why the iteration works."),
        step(13, "Interpret in the circuit context",
              "\\text{The circuit operates at approximately } 2.73 \\text{ A}",
              "The iterative method estimates the physical operating point without solving the cubic algebraically."),
    ],
    "(a) $f(2) < 0$, $f(3) > 0$. (b) $I_{1} = 2.5713$, $I_{2} = 2.8048$, $I_{3} = 2.7146$. (c) $I \\approx 2.73$ A.",
))

# ── q069 Hard: show_that convergence proof ──────────────────────────────────
questions.append(make_q(
    "q069", "Hard", 7, "exact",
    ["show that", "convergence", "trigonometric", "fixed point"],
    "Show that the iterative formula $x_{n+1} = \\cos x_{n}$ converges to the root of $x = \\cos x$ in $[0,\\,1]$, by proving that $|g'(x)| < 1$ for $g(x) = \\cos x$ on this interval.",
    [
        step(1, "Identify the iteration function",
             "g(x) = \\cos x",
             "The fixed-point equation $x = \\cos x$ is solved by iterating $g$."),
        step(2, "Differentiate $g(x)$",
             "g'(x) = -\\sin x",
             "The derivative of $\\cos x$ is $-\\sin x$."),
        step(3, "Find $|g'(x)|$ on $[0,\\,1]$",
             "|g'(x)| = |-\\sin x| = \\sin x",
             "Since $\\sin x \\geq 0$ on $[0,\\,1]$, the absolute value equals $\\sin x$."),
        step(4, "Determine the maximum of $\\sin x$ on $[0,\\,1]$",
             "\\sin x \\text{ is increasing on } [0,\\,1]",
             "The sine function increases from $0$ to $\\sin 1$ on this interval."),
        step(5, "Evaluate the maximum",
             "\\max_{[0,\\,1]} |g'(x)| = \\sin 1 \\approx 0.841",
             "The largest gradient magnitude on $[0,\\,1]$ is $\\sin 1 \\approx 0.841$."),
        step(6, "Conclude the gradient bound",
             "|g'(x)| \\leq 0.841 < 1 \\text{ for all } x \\in [0,\\,1]",
             "The convergence condition is satisfied throughout the interval."),
        step(7, "Verify a fixed point exists in $[0,\\,1]$",
             "h(x) = x - \\cos x; \\quad h(0) = -1, \\quad h(1) = 1 - \\cos 1 \\approx 0.460 > 0",
             "By the Intermediate Value Theorem, a root of $x = \\cos x$ lies in $(0,\\,1)$."),
        step(8, "Explain the contraction mapping",
             "|x_{n+1} - \\alpha| \\approx |g'(\\alpha)| \\cdot |x_{n} - \\alpha|",
             "Near the fixed point $\\alpha$, each error is multiplied by a factor less than $1$."),
        step(9, "Describe the cobweb for positive gradient",
             "g'(\\alpha) = -\\sin\\alpha < 0 \\Rightarrow \\text{ oscillating cobweb}",
             "Although $|g'| < 1$, the negative gradient means iterates bounce above and below the root."),
        step(10, "Note $\\alpha \\approx 0.7391$",
              "\\cos(0.7391) \\approx 0.7391",
              "The fixed point is approximately $0.7391$, within $[0,\\,1]$."),
        step(11, "Confirm $|g'(\\alpha)| < 1$ at the fixed point",
              "|g'(0.7391)| = \\sin(0.7391) \\approx 0.673 < 1",
              "At the actual fixed point, the gradient magnitude confirms convergence."),
        step(12, "State why starting in $[0,\\,1]$ works",
              "g([0,\\,1]) = [\\cos 1,\\, 1] \\approx [0.54,\\, 1] \\subset [0,\\, 1]",
              "The iteration maps $[0,\\,1]$ into itself, so iterates remain in the convergence region."),
        step(13, "State the conclusion",
              "\\text{Shown: } |g'(x)| < 1 \\text{ on } [0,\\,1], \\text{ so } x_{n+1} = \\cos x_{n} \\text{ converges}",
              "The gradient bound proves convergence of the iterative formula to the root of $x = \\cos x$."),
    ],
    "Shown: $|g'(x)| = \\sin x \\leq \\sin 1 \\approx 0.841 < 1$ on $[0,\\,1]$, so $x_{n+1} = \\cos x_{n}$ converges to the root of $x = \\cos x$.",
))

# ── q070 Hard: final comprehensive exam question ──────────────────────────────
questions.append(make_q(
    "q070", "Hard", 10, "decimal",
    ["change of sign", "iteration", "comparison", "stopping criterion", "comprehensive"],
    "Consider $f(x) = x^{3} - 2x - 5$.\n\n**(a)** Show that $f(x) = 0$ has a root $\\alpha$ in $[2,\\,3]$.\n\n**(b)** Use $x_{n+1} = \\sqrt[3]{2x_{n} + 5}$ with $x_{0} = 2.5$ to find $x_{1}$, $x_{2}$, $x_{3}$ and $x_{4}$ (to $4$ d.p.).\n\n**(c)** Show that $|g'(x)| < 1$ where $g(x) = \\sqrt[3]{2x + 5}$, and comment on convergence.\n\n**(d)** State $\\alpha$ to $2$ d.p. and describe when you would stop iterating in an exam.",
    [
        step(1, "Evaluate $f(2)$ for part (a)",
             "f(2) = 8 - 4 - 5 = -1",
             "At $x = 2$ the function is negative."),
        step(2, "Evaluate $f(3)$",
             "f(3) = 27 - 6 - 5 = 16",
             "At $x = 3$ the function is positive."),
        step(3, "Conclude part (a)",
             "f(2) < 0,\\; f(3) > 0 \\Rightarrow \\alpha \\in [2,\\,3]",
             "Change of sign on a continuous function guarantees a root."),
        step(4, "Set up the iteration for part (b)",
             "x_{n+1} = \\sqrt[3]{2x_{n} + 5}, \\quad x_{0} = 2.5",
             "Rearranging $x^{3} = 2x + 5$ gives the iterative formula."),
        step(5, "Compute $x_{1}$",
             "x_{1} = \\sqrt[3]{2(2.5) + 5} = \\sqrt[3]{10} = 2.1544",
             "The first iterate moves down from $2.5$."),
        step(6, "Compute $x_{2}$",
             "x_{2} = \\sqrt[3]{2(2.1544) + 5} = \\sqrt[3]{9.3088} = 2.1039",
             "The sequence approaches the root from above."),
        step(7, "Compute $x_{3}$",
             "x_{3} = \\sqrt[3]{2(2.1039) + 5} = \\sqrt[3]{9.2078} = 2.0946",
             "The iterates are very close to the known root $2.0946\\ldots$."),
        step(8, "Compute $x_{4}$",
             "x_{4} = \\sqrt[3]{2(2.0946) + 5} = \\sqrt[3]{9.1892} = 2.0940",
             "Further iteration refines the estimate."),
        step(9, "Differentiate $g(x) = \\sqrt[3]{2x + 5}$ for part (c)",
             "g'(x) = \\frac{2}{3\\sqrt[3]{(2x+5)^{2}}}",
             "The chain rule gives the gradient of the iteration function."),
        step(10, "Bound $|g'(x)|$ on $[2,\\,3]$",
              "x = 2: |g'(2)| = \\frac{2}{3\\sqrt[3]{81}} \\approx 0.154; \\quad x = 3: |g'(3)| = \\frac{2}{3\\sqrt[3]{121}} \\approx 0.126",
              "Both values are well below $1$, so $|g'(x)| < 1$ on $[2,\\,3]$."),
        step(11, "Comment on convergence",
              "|g'(\\alpha)| \\approx 0.13 \\Rightarrow \\text{ fast staircase convergence}",
              "A small gradient magnitude means errors shrink quickly at each step."),
        step(12, "State $\\alpha$ for part (d)",
              "\\alpha \\approx 2.09",
              "To $2$ decimal places, the root is $2.09$."),
        step(13, "Describe exam stopping criteria",
              "\\text{Stop when successive iterates agree to required accuracy}",
              "In an exam, stop when $|x_{n+1} - x_{n}|$ is less than half the unit of the last decimal place required, or when $x_{n}$ and $x_{n+1}$ round to the same value."),
        step(14, "Apply the stopping rule here",
              "|x_{4} - x_{3}| = 0.0006 < 0.005",
              "For $2$ d.p., successive iterates agree after $4$ steps."),
        step(15, "Verify $f(2.09) \\approx 0$",
              "f(2.09) = (2.09)^{3} - 2(2.09) - 5 \\approx -0.03",
              "Close to zero, confirming $\\alpha \\approx 2.09$ to $2$ d.p."),
        step(16, "Summarise all parts",
              "\\text{(a) } [2,3]; \\text{ (b) } x_{4} = 2.0940; \\text{ (c) } |g'| < 1; \\text{ (d) } \\alpha = 2.09",
              "This question combines location, iteration, convergence analysis, and stopping criteria."),
    ],
    "(a) $f(2) < 0$, $f(3) > 0$. (b) $x_{4} = 2.0940$. (c) $|g'(x)| < 1$ on $[2,\\,3]$, fast convergence. (d) $\\alpha \\approx 2.09$; stop when successive iterates agree to required d.p.",
))

assert len(questions) == 17, f"Expected 17 questions, got {len(questions)}"

for q in questions:
    n = len(q["workedSolution"]["steps"])
    diff = q["difficulty"]
    if diff == "Intermediate" and not (9 <= n <= 13):
        print(f"WARN {q['id']}: Intermediate has {n} steps")
    if diff == "Hard" and not (13 <= n <= 18):
        print(f"WARN {q['id']}: Hard has {n} steps")

write_questions_ts(
    OUT,
    questions,
    batch_label="Locating roots and iteration q054–q070",
)
print(f"Wrote {len(questions)} questions to {OUT}")
