#!/usr/bin/env python3
"""Generate q054-q070 for parametric differentiation subtopic."""
import json
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from question_ts import write_questions_ts

OUT = "/Users/benjaminwalpole/Wisest_Maths_V5/wisest-maths-content/src/data/questions/a-level-maths/year-2-pure/parametric-differentiation-q054-q070.ts"

SUBTOPIC = "Parametric differentiation"
SUBTOPIC_ID = "al.y2.pure.parametric-differentiation"


def make_q(qid, difficulty, marks, answer_type, tags, question_text, steps, final_answer):
    return {
        "id": f"{SUBTOPIC_ID}.{qid}",
        "level": "A-Level Maths",
        "topic": "Year 2 Pure",
        "subtopic": SUBTOPIC,
        "subtopicId": SUBTOPIC_ID,
        "difficulty": difficulty,
        "marks": marks,
        "answerType": answer_type,
        "tags": tags,
        "questionText": question_text,
        "questionDiagram": None,
        "workedSolution": {"steps": steps, "finalAnswer": final_answer},
    }


def step(n, desc, work, expl):
    return {
        "stepNumber": n,
        "description": desc,
        "workingLatex": work,
        "explanation": expl,
        "diagram": None,
    }


questions = []

# ── q054 Intermediate: evaluate dy/dx ─────────────────────────────────────────
questions.append(make_q(
    "q054", "Intermediate", 4, "exact",
    ["parametric differentiation", "chain rule", "gradient"],
    "A curve has parametric equations $x = t^{2} + 1$ and $y = t^{3} - 3t$. Find the value of $\\frac{dy}{dx}$ when $t = 2$.",
    [
        step(1, "Recall the parametric gradient formula",
             "\\frac{dy}{dx} = \\frac{dy/dt}{dx/dt}",
             "Because both $x$ and $y$ are expressed in terms of the same parameter $t$, the chain rule links the rates of change. Dividing $\\frac{dy}{dt}$ by $\\frac{dx}{dt}$ converts a gradient with respect to $t$ into a gradient with respect to $x$."),
        step(2, "Differentiate $x$ with respect to $t$",
             "\\frac{dx}{dt} = 2t",
             "Differentiating $t^{2}+1$ gives $2t$. The constant $1$ disappears because it does not change as $t$ changes."),
        step(3, "Differentiate $y$ with respect to $t$",
             "\\frac{dy}{dt} = 3t^{2} - 3",
             "The power rule on $t^{3}$ gives $3t^{2}$, and the linear term $-3t$ differentiates to $-3$."),
        step(4, "Write $\\frac{dy}{dx}$ in terms of $t$",
             "\\frac{dy}{dx} = \\frac{3t^{2} - 3}{2t}",
             "Substituting the two derivatives into the parametric formula gives the gradient at any value of $t$, provided $\\frac{dx}{dt} \\neq 0$."),
        step(5, "Evaluate $\\frac{dx}{dt}$ at $t = 2$",
             "\\left.\\frac{dx}{dt}\\right|_{t=2} = 2(2) = 4",
             "At $t = 2$ the curve is moving horizontally at rate $4$ units per unit change in $t$."),
        step(6, "Evaluate $\\frac{dy}{dt}$ at $t = 2$",
             "\\left.\\frac{dy}{dt}\\right|_{t=2} = 3(2)^{2} - 3 = 12 - 3 = 9",
             "At the same parameter value, the vertical rate of change is $9$."),
        step(7, "Form the gradient at $t = 2$",
             "\\left.\\frac{dy}{dx}\\right|_{t=2} = \\frac{9}{4}",
             "Dividing the vertical rate by the horizontal rate gives the slope of the tangent at the point corresponding to $t = 2$."),
        step(8, "Locate the point on the curve",
             "x = 2^{2} + 1 = 5, \\qquad y = 2^{3} - 3(2) = 2",
             "Substituting $t = 2$ into both parametric equations confirms the point is $(5,\\,2)$. A positive gradient means the curve is rising as $x$ increases there."),
        step(9, "State the final answer",
             "\\frac{dy}{dx} = \\frac{9}{4}",
             "The gradient of the curve at $t = 2$ is $\\frac{9}{4}$."),
    ],
    "$\\frac{dy}{dx} = \\dfrac{9}{4}$ when $t = 2$.",
))

# ── q055 Intermediate: second derivative ──────────────────────────────────────
questions.append(make_q(
    "q055", "Intermediate", 5, "exact",
    ["parametric differentiation", "second derivative", "quotient rule"],
    "A curve is defined by $x = 3t - t^{3}$ and $y = t^{2}$. Find $\\frac{d^{2}y}{dx^{2}}$ when $t = 0$.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             "\\frac{dx}{dt} = 3 - 3t^{2}, \\qquad \\frac{dy}{dt} = 2t",
             "These first derivatives are needed both for $\\frac{dy}{dx}$ and for the second-derivative formula."),
        step(2, "Write $\\frac{dy}{dx}$ as a function of $t$",
             "\\frac{dy}{dx} = \\frac{2t}{3 - 3t^{2}} = \\frac{2t}{3(1 - t^{2})}",
             "The quotient of the two first derivatives gives the gradient at each parameter value where $3 - 3t^{2} \\neq 0$."),
        step(3, "Recall the parametric second-derivative formula",
             "\\frac{d^{2}y}{dx^{2}} = \\frac{\\dfrac{d}{dt}\\!\\left(\\dfrac{dy}{dx}\\right)}{\\dfrac{dx}{dt}}",
             "To differentiate with respect to $x$, we first differentiate $\\frac{dy}{dx}$ with respect to $t$, then divide by $\\frac{dx}{dt}$. This is the parametric analogue of the chain rule for second derivatives."),
        step(4, "Differentiate the numerator and denominator of $\\frac{dy}{dx}$",
             "\\frac{d}{dt}(2t) = 2, \\qquad \\frac{d}{dt}\\bigl(3 - 3t^{2}\\bigr) = -6t",
             "These are the parts needed for the quotient rule when differentiating $\\frac{2t}{3-3t^{2}}$."),
        step(5, "Apply the quotient rule to $\\frac{dy}{dx}$",
             "\\frac{d}{dt}\\!\\left(\\frac{dy}{dx}\\right) = \\frac{2(3 - 3t^{2}) - 2t(-6t)}{(3 - 3t^{2})^{2}}",
             "The quotient rule gives $\\dfrac{u'v - uv'}{v^{2}}$ with $u = 2t$ and $v = 3 - 3t^{2}$."),
        step(6, "Simplify the numerator",
             "2(3 - 3t^{2}) + 12t^{2} = 6 - 6t^{2} + 12t^{2} = 6 + 6t^{2} = 6(1 + t^{2})",
             "Collecting like terms leaves a positive expression $6(1+t^{2})$, which is never zero."),
        step(7, "Write the simplified derivative",
             "\\frac{d}{dt}\\!\\left(\\frac{dy}{dx}\\right) = \\frac{6(1 + t^{2})}{(3 - 3t^{2})^{2}}",
             "The denominator is the square of $\\frac{dx}{dt}$, which keeps the expression compact."),
        step(8, "Evaluate at $t = 0$",
             "\\left.\\frac{d}{dt}\\!\\left(\\frac{dy}{dx}\\right)\\right|_{t=0} = \\frac{6(1)}{3^{2}} = \\frac{6}{9} = \\frac{2}{3}",
             "At $t = 0$ the numerator is $6$ and the denominator is $9$."),
        step(9, "Evaluate $\\frac{dx}{dt}$ at $t = 0$",
             "\\left.\\frac{dx}{dt}\\right|_{t=0} = 3",
             "The horizontal rate at $t = 0$ is $3$, so the second-derivative formula is valid here."),
        step(10, "Compute $\\frac{d^{2}y}{dx^{2}}$ at $t = 0$",
              "\\left.\\frac{d^{2}y}{dx^{2}}\\right|_{t=0} = \\frac{2/3}{3} = \\frac{2}{9}",
              "Dividing the result from step 8 by $\\frac{dx}{dt}$ completes the second-derivative calculation."),
        step(11, "Interpret the sign",
              "\\frac{d^{2}y}{dx^{2}} > 0 \\text{ at } t = 0",
              "A positive second derivative indicates the curve is concave up in the $x$-$y$ plane at this point, so any stationary point nearby would be a minimum."),
    ],
    "$\\dfrac{d^{2}y}{dx^{2}} = \\dfrac{2}{9}$ when $t = 0$.",
))

# ── q056 Intermediate: stationary points and nature ─────────────────────────
questions.append(make_q(
    "q056", "Intermediate", 6, "exact",
    ["parametric differentiation", "stationary points", "second derivative"],
    "A curve has parametric equations $x = t^{3} - 3t$ and $y = t^{2} - 4$. Find the coordinates of the stationary point on the curve and determine its nature.",
    [
        step(1, "State the condition for a stationary point",
             "\\frac{dy}{dx} = 0",
             "A stationary point occurs where the tangent is horizontal, meaning the gradient with respect to $x$ is zero."),
        step(2, "Find $\\frac{dx}{dt}$ and $\\frac{dy}{dt}$",
             "\\frac{dx}{dt} = 3t^{2} - 3 = 3(t^{2} - 1), \\qquad \\frac{dy}{dt} = 2t",
             "These first derivatives let us write $\\frac{dy}{dx}$ and test where it vanishes."),
        step(3, "Set up $\\frac{dy}{dx} = 0$",
             "\\frac{2t}{3(t^{2} - 1)} = 0",
             "A fraction equals zero only when its numerator is zero (and the denominator is non-zero)."),
        step(4, "Solve for $t$",
             "2t = 0 \\Rightarrow t = 0",
             "The only solution is $t = 0$. At this value, $\\frac{dx}{dt} = -3 \\neq 0$, so the stationary-point condition is valid."),
        step(5, "Find the coordinates at $t = 0$",
             "x = 0^{3} - 3(0) = 0, \\qquad y = 0^{2} - 4 = -4",
             "The stationary point is $(0,\\,-4)$."),
        step(6, "Recall the second-derivative test",
             "\\frac{d^{2}y}{dx^{2}} = \\frac{\\dfrac{d}{dt}\\!\\left(\\dfrac{dy}{dx}\\right)}{\\dfrac{dx}{dt}}",
             "The sign of the second derivative at a stationary point tells us whether the curve is concave up (minimum) or concave down (maximum)."),
        step(7, "Differentiate $\\frac{dy}{dx}$ with respect to $t$",
             "\\frac{d}{dt}\\!\\left(\\frac{2t}{3(t^{2}-1)}\\right) = \\frac{2 \\cdot 3(t^{2}-1) - 2t \\cdot 6t}{9(t^{2}-1)^{2}} = \\frac{6(t^{2}-1) - 12t^{2}}{9(t^{2}-1)^{2}}",
             "Applying the quotient rule and simplifying the numerator is the key algebraic step."),
        step(8, "Simplify the numerator at $t = 0$",
             "6(0 - 1) - 0 = -6",
             "At $t = 0$ the numerator is $-6$, so $\\frac{d}{dt}\\!\\left(\\frac{dy}{dx}\\right) = \\frac{-6}{9(-1)^{2}} = -\\frac{2}{3}$."),
        step(9, "Evaluate $\\frac{d^{2}y}{dx^{2}}$ at $t = 0$",
             "\\left.\\frac{d^{2}y}{dx^{2}}\\right|_{t=0} = \\frac{-2/3}{-3} = \\frac{2}{9} > 0",
             "Dividing by $\\frac{dx}{dt} = -3$ gives a positive second derivative."),
        step(10, "State the nature of the stationary point",
              "\\text{Minimum at } (0,\\,-4)",
              "Because $\\frac{d^{2}y}{dx^{2}} > 0$, the curve is concave up at the stationary point, so $(0,\\,-4)$ is a local minimum."),
    ],
    "Stationary point $(0,\\,-4)$; local minimum.",
))

# ── q057 Intermediate: tangent meets axes ─────────────────────────────────────
questions.append(make_q(
    "q057", "Intermediate", 5, "exact",
    ["parametric differentiation", "tangent", "area"],
    "A curve is given by $x = 2t$ and $y = t^{2}$. The tangent at the point where $t = 1$ meets the coordinate axes at $A$ and $B$. Find the area of triangle $OAB$, where $O$ is the origin.",
    [
        step(1, "Find the point on the curve when $t = 1$",
             "x = 2(1) = 2, \\qquad y = 1^{2} = 1",
             "The tangent is drawn at $P(2,\\,1)$."),
        step(2, "Differentiate the parametric equations",
             "\\frac{dx}{dt} = 2, \\qquad \\frac{dy}{dt} = 2t",
             "Both coordinates change smoothly with $t$, so we need their rates of change to find the gradient."),
        step(3, "Find the gradient at $t = 1$",
             "\\left.\\frac{dy}{dx}\\right|_{t=1} = \\frac{2(1)}{2} = 1",
             "At $t = 1$ the tangent has gradient $1$, so it rises one unit vertically for each unit horizontally."),
        step(4, "Write the equation of the tangent",
             "y - 1 = 1(x - 2) \\;\\Rightarrow\\; y = x - 2",
             "Using point-gradient form through $(2,\\,1)$ with $m = 1$ gives the tangent line."),
        step(5, "Find where the tangent meets the $x$-axis",
             "0 = x - 2 \\Rightarrow x = 2",
             "Setting $y = 0$ gives the $x$-intercept $A(2,\\,0)$."),
        step(6, "Find where the tangent meets the $y$-axis",
             "y = 0 - 2 = -2",
             "Setting $x = 0$ gives the $y$-intercept $B(0,\\,-2)$."),
        step(7, "Identify the triangle vertices",
             "O(0,\\,0), \\quad A(2,\\,0), \\quad B(0,\\,-2)",
             "The tangent cuts the axes at $A$ and $B$, and the origin completes the triangle."),
        step(8, "Calculate the lengths of the legs",
             "OA = 2, \\qquad OB = 2",
             "Both intercepts are $2$ units from the origin along perpendicular axes."),
        step(9, "Find the area of triangle $OAB$",
             "\\text{Area} = \\frac{1}{2} \\times 2 \\times 2 = 2",
             "For a right-angled triangle with legs along the axes, the area is half the product of the intercept lengths."),
        step(10, "State the final answer",
              "\\text{Area} = 2 \\text{ square units}",
              "The tangent at $t = 1$ forms a triangle of area $2$ with the coordinate axes."),
    ],
    "Area of triangle $OAB = 2$ square units.",
))

# ── q058 Intermediate: normal length ──────────────────────────────────────────
questions.append(make_q(
    "q058", "Intermediate", 5, "exact",
    ["parametric differentiation", "normal", "circle"],
    "A curve has parametric equations $x = 1 + 2\\cos t$ and $y = 2\\sin t$. Find the length of the normal from the point on the curve where $t = \\dfrac{\\pi}{3}$ to the point where the normal meets the $x$-axis.",
    [
        step(1, "Find the coordinates when $t = \\dfrac{\\pi}{3}$",
             "x = 1 + 2\\cos\\!\\left(\\frac{\\pi}{3}\\right) = 1 + 2 \\times \\frac{1}{2} = 2, \\qquad y = 2\\sin\\!\\left(\\frac{\\pi}{3}\\right) = 2 \\times \\frac{\\sqrt{3}}{2} = \\sqrt{3}",
             "The point on the curve is $P\\!\\left(2,\\,\\sqrt{3}\\right)$."),
        step(2, "Differentiate with respect to $t$",
             "\\frac{dx}{dt} = -2\\sin t, \\qquad \\frac{dy}{dt} = 2\\cos t",
             "These describe how the point moves around the ellipse as $t$ changes."),
        step(3, "Find the tangent gradient at $t = \\dfrac{\\pi}{3}$",
             "\\left.\\frac{dy}{dx}\\right|_{t=\\pi/3} = \\frac{2 \\times \\frac{1}{2}}{-2 \\times \\frac{\\sqrt{3}}{2}} = \\frac{1}{-\\sqrt{3}} = -\\frac{1}{\\sqrt{3}}",
             "The tangent slope uses $\\sin(\\pi/3) = \\sqrt{3}/2$ and $\\cos(\\pi/3) = 1/2$."),
        step(4, "Find the normal gradient",
             "m_{\\text{normal}} = -\\frac{1}{m_{\\text{tangent}}} = -\\frac{1}{-1/\\sqrt{3}} = \\sqrt{3}",
             "The normal is perpendicular to the tangent, so its gradient is the negative reciprocal."),
        step(5, "Write the equation of the normal",
             "y - \\sqrt{3} = \\sqrt{3}(x - 2)",
             "The normal passes through $P\\!\\left(2,\\,\\sqrt{3}\\right)$ with gradient $\\sqrt{3}$."),
        step(6, "Find where the normal meets the $x$-axis",
             "0 - \\sqrt{3} = \\sqrt{3}(x - 2) \\Rightarrow -1 = x - 2 \\Rightarrow x = 1",
             "Setting $y = 0$ locates the $x$-intercept at $(1,\\,0)$."),
        step(7, "Set up the distance formula",
             "PQ = \\sqrt{(2 - 1)^{2} + (\\sqrt{3} - 0)^{2}}",
             "The normal length is the distance from $P(2,\\,\\sqrt{3})$ to $Q(1,\\,0)$."),
        step(8, "Evaluate the distance",
             "PQ = \\sqrt{1 + 3} = \\sqrt{4} = 2",
             "The horizontal separation is $1$ and the vertical separation is $\\sqrt{3}$, giving a hypotenuse of $2$."),
        step(9, "State the final answer",
             "\\text{Length of normal} = 2",
             "The normal from $P$ to the $x$-axis has length $2$ units."),
    ],
    "Length of the normal $= 2$ units.",
))

# ── q059 Hard: parallel tangents ──────────────────────────────────────────────
questions.append(make_q(
    "q059", "Hard", 6, "exact",
    ["parametric differentiation", "parallel tangents", "quadratic"],
    "A curve has parametric equations $x = t^{2}$ and $y = t^{3} - 3t$. Find the two values of $t$ for which the tangent to the curve is parallel to the line $y = 3x$.",
    [
        step(1, "Identify the required gradient",
             "m = 3",
             "Parallel lines share the same gradient, so we need $\\frac{dy}{dx} = 3$."),
        step(2, "Differentiate the parametric equations",
             "\\frac{dx}{dt} = 2t, \\qquad \\frac{dy}{dt} = 3t^{2} - 3",
             "The first derivatives of both coordinates are needed for the parametric gradient formula."),
        step(3, "Write $\\frac{dy}{dx}$ in terms of $t$",
             "\\frac{dy}{dx} = \\frac{3t^{2} - 3}{2t}",
             "This gives the tangent gradient at each parameter value where $t \\neq 0$."),
        step(4, "Set the gradient equal to $3$",
             "\\frac{3t^{2} - 3}{2t} = 3",
             "We solve this equation to find the parameter values where the tangent is parallel to $y = 3x$."),
        step(5, "Clear the fraction",
             "3t^{2} - 3 = 6t",
             "Multiplying both sides by $2t$ is valid provided $t \\neq 0$. We will check separately whether $t = 0$ could work."),
        step(6, "Rearrange into standard quadratic form",
             "3t^{2} - 6t - 3 = 0",
             "Collecting all terms on one side gives a quadratic in $t$."),
        step(7, "Divide through by $3$",
             "t^{2} - 2t - 1 = 0",
             "Simplifying makes the quadratic formula cleaner."),
        step(8, "Apply the quadratic formula",
             "t = \\frac{2 \\pm \\sqrt{4 + 4}}{2} = \\frac{2 \\pm 2\\sqrt{2}}{2} = 1 \\pm \\sqrt{2}",
             "The discriminant is $4 + 4 = 8$, giving two distinct real solutions."),
        step(9, "Verify $t = 1 + \\sqrt{2}$",
             "\\frac{3(1+\\sqrt{2})^{2} - 3}{2(1+\\sqrt{2})} = \\frac{3(3+2\\sqrt{2}) - 3}{2(1+\\sqrt{2})} = \\frac{6+6\\sqrt{2}}{2(1+\\sqrt{2})} = 3",
             "Substituting $t = 1 + \\sqrt{2}$ back into the gradient formula confirms the tangent gradient is $3$."),
        step(10, "Verify $t = 1 - \\sqrt{2}$",
              "\\frac{3(1-\\sqrt{2})^{2} - 3}{2(1-\\sqrt{2})} = \\frac{3(3-2\\sqrt{2}) - 3}{2(1-\\sqrt{2})} = \\frac{6-6\\sqrt{2}}{2(1-\\sqrt{2})} = 3",
              "The second root also gives gradient $3$, as expected from the quadratic equation."),
        step(11, "Find the coordinates at each value of $t$",
              "t = 1+\\sqrt{2}: ( (1+\\sqrt{2})^{2},\\, (1+\\sqrt{2})^{3}-3(1+\\sqrt{2}) ); \\quad t = 1-\\sqrt{2}: ( (1-\\sqrt{2})^{2},\\, (1-\\sqrt{2})^{3}-3(1-\\sqrt{2}) )",
              "Each valid $t$ corresponds to a distinct point on the curve where the tangent is parallel to $y = 3x$."),
        step(12, "Verify $t = 0$ is not a solution",
             "\\left.\\frac{dy}{dx}\\right|_{t=0} \\text{ is undefined}",
             "At $t = 0$ we have $\\frac{dx}{dt} = 0$, so the tangent is vertical and cannot be parallel to a line of gradient $3$."),
        step(13, "State the values of $t$",
              "t = 1 + \\sqrt{2} \\quad \\text{and} \\quad t = 1 - \\sqrt{2}",
              "These are the two parameter values where the tangent is parallel to $y = 3x$."),
    ],
    "$t = 1 + \\sqrt{2}$ and $t = 1 - \\sqrt{2}$.",
))

# ── q060 Hard: perpendicular tangents ───────────────────────────────────────
questions.append(make_q(
    "q060", "Hard", 6, "exact",
    ["parametric differentiation", "perpendicular tangents", "quadratic"],
    "A curve is defined by $x = t^{2} - 1$ and $y = t^{3} + t$. Find the values of $t$ for which the tangent to the curve is perpendicular to the line $2x + y = 5$.",
    [
        step(1, "Find the gradient of the given line",
             "2x + y = 5 \\Rightarrow y = -2x + 5, \\quad m_{\\text{line}} = -2",
             "Rewriting in slope-intercept form reveals the line has gradient $-2$."),
        step(2, "State the perpendicular gradient condition",
             "m_{\\text{tangent}} \\times m_{\\text{line}} = -1 \\Rightarrow m_{\\text{tangent}} = \\frac{1}{2}",
             "Perpendicular gradients multiply to $-1$, so the tangent must have gradient $\\frac{1}{2}$."),
        step(3, "Differentiate the parametric equations",
             "\\frac{dx}{dt} = 2t, \\qquad \\frac{dy}{dt} = 3t^{2} + 1",
             "Both derivatives are needed to form $\\frac{dy}{dx}$."),
        step(4, "Write $\\frac{dy}{dx}$ and set it equal to $\\dfrac{1}{2}$",
             "\\frac{3t^{2} + 1}{2t} = \\frac{1}{2}",
             "The tangent gradient must equal $\\frac{1}{2}$ for perpendicularity."),
        step(5, "Clear the fraction (for $t \\neq 0$)",
             "3t^{2} + 1 = t",
             "Multiplying both sides by $2t$ gives a polynomial equation."),
        step(6, "Rearrange into quadratic form",
             "3t^{2} - t + 1 = 0",
             "All terms are collected on one side."),
        step(7, "Compute the discriminant",
             "b^{2} - 4ac = (-1)^{2} - 4(3)(1) = 1 - 12 = -11 < 0",
             "A negative discriminant means there are no real solutions."),
        step(8, "Apply the quadratic formula formally",
             "t = \\frac{1 \\pm \\sqrt{-11}}{6}",
             "Even though the roots are complex, writing the formula confirms no real $t$ satisfies the equation."),
        step(9, "Analyse the sign of $\\frac{dy}{dx}$ for $t > 0$",
             "\\frac{3t^{2}+1}{2t} > 0 \\text{ for all } t > 0",
             "For positive $t$ both numerator and denominator are positive, so the tangent gradient is always positive and can never equal $\\frac{1}{2}$ from the perpendicular condition alone — but more importantly the equation has no real roots at all."),
        step(10, "Analyse the sign of $\\frac{dy}{dx}$ for $t < 0$",
              "\\frac{3t^{2}+1}{2t} < 0 \\text{ for all } t < 0",
              "For negative $t$ the gradient is always negative, while the required gradient $\\frac{1}{2}$ is positive, so no solution is possible on this branch either."),
        step(11, "Interpret the geometric result",
              "\\text{No real values of } t",
              "Because the quadratic has no real roots, no point on the curve has a tangent perpendicular to the given line."),
        step(12, "Confirm $t = 0$ does not work",
             "\\left.\\frac{dy}{dx}\\right|_{t=0} \\text{ is undefined}",
             "At $t = 0$, $\\frac{dx}{dt} = 0$ so the tangent is vertical, which cannot be perpendicular to a line of finite gradient."),
        step(13, "State the conclusion",
              "\\text{There are no values of } t",
              "The curve never has a tangent perpendicular to $2x + y = 5$."),
    ],
    "There are no real values of $t$; the tangent is never perpendicular to $2x + y = 5$.",
))

# ── q061 Hard: second derivative and nature ───────────────────────────────────
questions.append(make_q(
    "q061", "Hard", 7, "exact",
    ["parametric differentiation", "second derivative", "stationary points", "nature"],
    "A curve has parametric equations $x = t + \\dfrac{1}{t}$ and $y = t - \\dfrac{1}{t}$, for $t > 0$. Find all stationary points and determine the nature of each.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             "\\frac{dx}{dt} = 1 - \\frac{1}{t^{2}}, \\qquad \\frac{dy}{dt} = 1 + \\frac{1}{t^{2}}",
             "Using the power rule on $t^{-1}$ gives $-t^{-2}$ for each reciprocal term."),
        step(2, "Write $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{1 + \\dfrac{1}{t^{2}}}{1 - \\dfrac{1}{t^{2}}} = \\frac{t^{2} + 1}{t^{2} - 1}",
             "Multiplying numerator and denominator by $t^{2}$ clears the fractions."),
        step(3, "Set $\\frac{dy}{dx} = 0$",
             "t^{2} + 1 = 0",
             "A fraction is zero only when its numerator is zero. Here $t^{2} + 1 = 0$ has no real solutions."),
        step(4, "Check whether $\\frac{dx}{dt} = 0$ at any point",
             "1 - \\frac{1}{t^{2}} = 0 \\Rightarrow t^{2} = 1 \\Rightarrow t = 1 \\quad (t > 0)",
             "When $\\frac{dx}{dt} = 0$ but $\\frac{dy}{dt} \\neq 0$, the tangent is vertical rather than horizontal."),
        step(5, "Evaluate $\\frac{dy}{dt}$ at $t = 1$",
             "\\left.\\frac{dy}{dt}\\right|_{t=1} = 1 + 1 = 2 \\neq 0",
             "At $t = 1$ the curve has a vertical tangent, not a horizontal one."),
        step(6, "Find the coordinates at $t = 1$",
             "x = 1 + 1 = 2, \\qquad y = 1 - 1 = 0",
             "The point $(2,\\,0)$ has a vertical tangent."),
        step(7, "Analyse the sign of $\\frac{dy}{dx}$ either side of $t = 1$",
             "t \\to 1^{-}: \\frac{dy}{dx} \\to -\\infty; \\qquad t \\to 1^{+}: \\frac{dy}{dx} \\to +\\infty",
             "The gradient jumps from large negative to large positive, confirming a vertical tangent at $t = 1$."),
        step(8, "Differentiate $\\frac{dy}{dx}$ for the second derivative",
             "\\frac{d}{dt}\\!\\left(\\frac{t^{2}+1}{t^{2}-1}\\right) = \\frac{2t(t^{2}-1) - (t^{2}+1)(2t)}{(t^{2}-1)^{2}} = \\frac{-4t}{(t^{2}-1)^{2}}",
             "The quotient rule simplifies to $-4t$ in the numerator."),
        step(9, "Evaluate $\\frac{d^{2}y}{dx^{2}}$ near $t = 1$",
             "\\frac{d^{2}y}{dx^{2}} = \\frac{-4t}{(t^{2}-1)^{2} \\cdot \\left(1 - \\frac{1}{t^{2}}\\right)}",
             "At a vertical tangent, the standard second-derivative test for stationary points does not apply because $\\frac{dy}{dx}$ is undefined."),
        step(10, "Conclude about stationary points",
              "\\text{No stationary points for } t > 0",
              "Since $\\frac{dy}{dx}$ is never zero for real $t$, the curve has no horizontal tangents and therefore no stationary points."),
        step(11, "Note the vertical tangent",
              "\\text{Vertical tangent at } (2,\\,0) \\text{ when } t = 1",
              "The only special point is $(2,\\,0)$ where the tangent is vertical. This is a cusp-like feature in the parametric trace."),
        step(12, "Explain why $\\frac{dy}{dx}$ is never zero",
              "t^{2} + 1 \\geqslant 1 > 0 \\text{ for all real } t",
              "The numerator of $\\frac{dy}{dx}$ is always positive, so the gradient never vanishes and there can be no stationary points."),
        step(13, "State the final answer",
              "\\text{No stationary points; vertical tangent at } (2,\\,0)",
              "The curve has no stationary points for $t > 0$. The point $(2,\\,0)$ at $t = 1$ has a vertical tangent."),
    ],
    "No stationary points. Vertical tangent at $(2,\\,0)$ when $t = 1$.",
))

# ── q062 Hard: tangent meets axes (harder curve) ──────────────────────────────
questions.append(make_q(
    "q062", "Hard", 7, "exact",
    ["parametric differentiation", "tangent", "axes intercepts", "area"],
    "A curve has parametric equations $x = t^{2}$ and $y = t^{3} - 4t$. The tangent at the point where $t = 2$ meets the $x$-axis at $A$ and the $y$-axis at $B$. Find the coordinates of $A$ and $B$, and the area of triangle $OAB$ where $O$ is the origin.",
    [
        step(1, "Find the point on the curve at $t = 2$",
             "x = 2^{2} = 4, \\qquad y = 2^{3} - 4(2) = 8 - 8 = 0",
             "The point is $P(4,\\,0)$, which lies on the $x$-axis."),
        step(2, "Differentiate with respect to $t$",
             "\\frac{dx}{dt} = 2t, \\qquad \\frac{dy}{dt} = 3t^{2} - 4",
             "These first derivatives determine the tangent gradient."),
        step(3, "Find the gradient at $t = 2$",
             "\\left.\\frac{dy}{dx}\\right|_{t=2} = \\frac{3(4) - 4}{2(2)} = \\frac{8}{4} = 2",
             "The tangent at $P$ has gradient $2$."),
        step(4, "Write the tangent equation",
             "y - 0 = 2(x - 4) \\Rightarrow y = 2x - 8",
             "Using point-gradient form through $(4,\\,0)$ with $m = 2$."),
        step(5, "Find the $x$-intercept $A$",
             "0 = 2x - 8 \\Rightarrow x = 4",
             "The tangent meets the $x$-axis at $A(4,\\,0)$, which coincides with $P$."),
        step(6, "Find the $y$-intercept $B$",
             "y = 2(0) - 8 = -8",
             "Setting $x = 0$ gives $B(0,\\,-8)$."),
        step(7, "Identify the triangle",
             "O(0,\\,0), \\quad A(4,\\,0), \\quad B(0,\\,-8)",
             "The triangle has vertices at the origin and the two axis intercepts."),
        step(8, "Calculate the leg lengths",
             "OA = 4, \\qquad OB = 8",
             "The intercepts are $4$ units along the $x$-axis and $8$ units along the $y$-axis."),
        step(9, "Find the area",
             "\\text{Area} = \\frac{1}{2} \\times 4 \\times 8 = 16",
             "Half the product of the perpendicular leg lengths gives the triangle area."),
        step(10, "Interpret the geometry",
              "\\text{Right-angled triangle with legs } 4 \\text{ and } 8",
              "Because the tangent cuts both axes at right angles through the origin, the area formula for a right triangle applies directly."),
        step(11, "Note that $P$ lies on the $x$-axis",
              "P = A = (4,\\,0)",
              "Since the point of tangency already lies on the $x$-axis, one vertex of the triangle coincides with $A$."),
        step(12, "Confirm the tangent equation by substitution",
              "\\text{At } x = 0: y = -8; \\quad \\text{at } x = 4: y = 0",
              "Substituting the intercept $x$-values back into $y = 2x - 8$ confirms both axis crossings."),
        step(13, "State the final answer",
              "A(4,\\,0),\\; B(0,\\,-8),\\; \\text{Area} = 16",
              "The tangent meets the axes at $A(4,\\,0)$ and $B(0,\\,-8)$, forming a triangle of area $16$ square units with the origin."),
    ],
    "$A(4,\\,0)$, $B(0,\\,-8)$, area $= 16$ square units.",
))

# ── q063 Hard: normal length ──────────────────────────────────────────────────
questions.append(make_q(
    "q063", "Hard", 7, "exact",
    ["parametric differentiation", "normal", "distance"],
    "A curve has parametric equations $x = 2t$ and $y = t^{2} + 1$. Find the length of the normal from the point on the curve where $t = 1$ to the point where the normal meets the $x$-axis.",
    [
        step(1, "Find the coordinates of $P$ when $t = 1$",
             "x = 2(1) = 2, \\qquad y = 1^{2} + 1 = 2",
             "The point on the curve is $P(2,\\,2)$."),
        step(2, "Differentiate with respect to $t$",
             "\\frac{dx}{dt} = 2, \\qquad \\frac{dy}{dt} = 2t",
             "Both coordinates change with $t$, so we need their rates of change to find the tangent gradient."),
        step(3, "Find the tangent gradient at $t = 1$",
             "\\left.\\frac{dy}{dx}\\right|_{t=1} = \\frac{2(1)}{2} = 1",
             "The tangent at $P$ has gradient $1$, so it makes a $45^{\\circ}$ angle with the positive $x$-axis."),
        step(4, "Find the normal gradient",
             "m_{\\text{normal}} = -\\frac{1}{1} = -1",
             "The normal is perpendicular to the tangent, so its gradient is the negative reciprocal of $1$."),
        step(5, "Write the equation of the normal",
             "y - 2 = -1(x - 2)",
             "Using point-gradient form through $P(2,\\,2)$ with gradient $-1$."),
        step(6, "Simplify the normal equation",
             "y = -x + 4",
             "Expanding and collecting terms gives a convenient form for finding intercepts."),
        step(7, "Find where the normal meets the $x$-axis",
             "0 = -x + 4 \\Rightarrow x = 4",
             "Setting $y = 0$ locates the $x$-intercept at $Q(4,\\,0)$."),
        step(8, "Identify the horizontal separation",
             "4 - 2 = 2",
             "The $x$-coordinates of $P$ and $Q$ differ by $2$ units."),
        step(9, "Identify the vertical separation",
             "0 - 2 = -2",
             "The $y$-coordinates differ by $2$ units in magnitude."),
        step(10, "Set up the distance formula",
              "PQ = \\sqrt{(4 - 2)^{2} + (0 - 2)^{2}}",
              "The length of the normal segment is the straight-line distance from $P$ to $Q$."),
        step(11, "Evaluate the squared distance",
              "PQ^{2} = 2^{2} + (-2)^{2} = 4 + 4 = 8",
              "Squaring each separation and adding gives $8$."),
        step(12, "Take the square root",
              "PQ = \\sqrt{8} = 2\\sqrt{2}",
              "The exact length simplifies to $2\\sqrt{2}$ units."),
        step(13, "Check using the geometry of a $45^{\\circ}$ normal",
              "\\text{Right triangle with equal legs of length } 2",
              "Because the normal has gradient $-1$, the horizontal and vertical separations are equal, forming an isosceles right triangle with hypotenuse $2\\sqrt{2}$."),
    ],
    "$PQ = 2\\sqrt{2}$ units.",
))

# ── q064 Hard: multi-part gradient and tangent ────────────────────────────────
questions.append(make_q(
    "q064", "Hard", 8, "exact",
    ["parametric differentiation", "tangent", "normal", "multi-part"],
    "A curve $C$ has parametric equations $x = 3t - t^{3}$ and $y = 2t^{2}$.\n\n**(a)** Find $\\dfrac{dy}{dx}$ in terms of $t$.\n\n**(b)** Find the equation of the tangent to $C$ at the point where $t = 1$, giving your answer in the form $ax + by + c = 0$.\n\n**(c)** Find the equation of the normal to $C$ at the same point.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             "\\frac{dx}{dt} = 3 - 3t^{2}, \\qquad \\frac{dy}{dt} = 4t",
             "These are the building blocks for every part of the question."),
        step(2, "Part (a): write $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{4t}{3 - 3t^{2}} = \\frac{4t}{3(1 - t^{2})}",
             "Dividing $\\frac{dy}{dt}$ by $\\frac{dx}{dt}$ gives the gradient formula for any $t$ where $t \\neq \\pm 1$."),
        step(3, "Part (b): find the point at $t = 1$",
             "x = 3(1) - 1 = 2, \\qquad y = 2(1)^{2} = 2",
             "The point on the curve is $(2,\\,2)$."),
        step(4, "Evaluate the gradient at $t = 1$",
             "\\left.\\frac{dy}{dx}\\right|_{t=1} = \\frac{4}{3 - 3} \\text{ is undefined}",
             "At $t = 1$, $\\frac{dx}{dt} = 0$, so the tangent is vertical."),
        step(5, "Write the vertical tangent equation",
             "x = 2",
             "A vertical line through $x = 2$ is the tangent at $t = 1$."),
        step(6, "Express in the form $ax + by + c = 0$",
             "x - 2 = 0",
             "This is the required form with $a = 1$, $b = 0$, $c = -2$."),
        step(7, "Part (c): identify the normal gradient",
             "m_{\\text{normal}} = 0",
             "A line perpendicular to a vertical line is horizontal, so the normal has gradient $0$."),
        step(8, "Write the normal equation",
             "y = 2",
             "The horizontal line through $(2,\\,2)$ is the normal."),
        step(9, "Verify perpendicularity",
             "\\text{Vertical tangent } x = 2 \\perp \\text{ horizontal normal } y = 2",
             "A vertical and a horizontal line are always perpendicular, confirming our answer."),
        step(10, "Summarise part (a)",
              "\\frac{dy}{dx} = \\dfrac{4t}{3(1 - t^{2})}",
              "This gradient formula is valid for $t \\neq \\pm 1$."),
        step(11, "Summarise parts (b) and (c)",
              "\\text{Tangent: } x - 2 = 0; \\qquad \\text{Normal: } y = 2",
              "At $t = 1$ the curve has a vertical tangent and a horizontal normal through $(2,\\,2)$."),
        step(12, "Note the geometric feature",
              "t = 1 \\text{ gives a turning point in the } x\\text{-direction}",
              "When $\\frac{dx}{dt} = 0$ the curve momentarily stops moving horizontally, creating a vertical tangent in the $xy$-plane."),
        step(13, "State all three answers clearly",
              "\\text{(a) } \\frac{dy}{dx} = \\frac{4t}{3(1-t^{2})}; \\quad \\text{(b) } x - 2 = 0; \\quad \\text{(c) } y = 2",
              "The gradient formula, vertical tangent, and horizontal normal together describe the curve's behaviour at $t = 1$."),
    ],
    "(a) $\\dfrac{dy}{dx} = \\dfrac{4t}{3(1-t^{2})}$; (b) tangent $x - 2 = 0$; (c) normal $y = 2$.",
))

# ── q065 Hard: find t for given gradient ──────────────────────────────────────
questions.append(make_q(
    "q065", "Hard", 7, "exact",
    ["parametric differentiation", "parallel tangents", "quadratic"],
    "A curve has parametric equations $x = t^{2} + 2t$ and $y = t^{3} + t$. Find all values of $t$ for which the tangent to the curve has gradient $-1$.",
    [
        step(1, "Differentiate with respect to $t$",
             "\\frac{dx}{dt} = 2t + 2, \\qquad \\frac{dy}{dt} = 3t^{2} + 1",
             "The parametric gradient formula requires both first derivatives."),
        step(2, "Write $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{3t^{2} + 1}{2t + 2}",
             "This fraction gives the tangent gradient at each $t$ where $2t + 2 \\neq 0$."),
        step(3, "Set the gradient equal to $-1$",
             "\\frac{3t^{2} + 1}{2t + 2} = -1",
             "We solve for the parameter values where the tangent has gradient $-1$."),
        step(4, "Clear the denominator",
             "3t^{2} + 1 = -(2t + 2)",
             "Multiplying by $2t + 2$ requires $t \\neq -1$; we check that case separately."),
        step(5, "Expand and collect terms",
             "3t^{2} + 1 = -2t - 2 \\Rightarrow 3t^{2} + 2t + 3 = 0",
             "All terms are moved to one side to form a standard quadratic."),
        step(6, "Compute the discriminant",
             "\\Delta = 2^{2} - 4(3)(3) = 4 - 36 = -32 < 0",
             "A negative discriminant means no real solutions exist."),
        step(7, "Check the excluded value $t = -1$",
             "\\left.\\frac{dy}{dx}\\right|_{t=-1} \\text{ is undefined}",
             "At $t = -1$, $\\frac{dx}{dt} = 0$ so the tangent is vertical, not of gradient $-1$."),
        step(8, "Interpret the result",
             "\\text{No real values of } t",
             "The quadratic has no real roots, and the excluded case does not help, so no tangent has gradient $-1$."),
        step(9, "Verify by sketching the gradient behaviour",
             "\\frac{3t^{2}+1}{2t+2} > 0 \\text{ for } t > -1",
             "For $t > -1$ the numerator is always positive, so the gradient is always positive and can never equal $-1$."),
        step(10, "Analyse $t < -1$",
              "\\frac{3t^{2}+1}{2t+2} < 0 \\text{ for } t < -1",
              "For $t < -1$ the gradient is negative, but the quadratic still has no real roots, confirming no exact match."),
        step(11, "Apply the quadratic formula formally",
              "t = \\frac{-2 \\pm \\sqrt{-32}}{6}",
              "The negative discriminant confirms the roots are complex, so no real parameter value produces gradient $-1$."),
        step(12, "Explain the physical meaning",
              "\\text{The tangent gradient never equals } -1",
              "The curve's tangent slopes are either positive (for $t > -1$) or undefined at $t = -1$, so a gradient of exactly $-1$ is never achieved."),
        step(13, "State the conclusion",
              "\\text{There are no values of } t",
              "No point on the curve has a tangent of gradient $-1$."),
    ],
    "There are no real values of $t$.",
))

# ── q066 Hard: gradient in context (projectile) ───────────────────────────────
questions.append(make_q(
    "q066", "Hard", 8, "exact",
    ["parametric differentiation", "modelling", "projectile", "gradient"],
    "A ball is projected from a platform. Its position $t$ seconds after projection is modelled by $x = 12t$ metres and $y = 20t - 5t^{2}$ metres, where $t \\geqslant 0$.\n\n**(a)** Find $\\dfrac{dy}{dx}$ in terms of $t$ and explain what it represents.\n\n**(b)** Find the gradient of the path when $t = 2$, and interpret this value in context.\n\n**(c)** Find the value of $t$ when the ball is moving horizontally.",
    [
        step(1, "Differentiate the position equations",
             "\\frac{dx}{dt} = 12, \\qquad \\frac{dy}{dt} = 20 - 10t",
             "The horizontal speed is constant at $12$ m/s, while the vertical speed decreases under gravity."),
        step(2, "Part (a): form $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{20 - 10t}{12} = \\frac{5 - 2.5t}{3}",
             "Dividing vertical velocity by horizontal velocity gives the slope of the path in the $xy$-plane."),
        step(3, "Explain the meaning of $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\text{gradient of the path at time } t",
             "This measures how steeply the ball is rising or falling relative to its horizontal displacement. It is the tangent slope to the trajectory, not the speed."),
        step(4, "Part (b): substitute $t = 2$",
             "\\left.\\frac{dy}{dx}\\right|_{t=2} = \\frac{20 - 20}{12} = 0",
             "At $t = 2$ seconds the gradient of the path is zero."),
        step(5, "Interpret the gradient at $t = 2$",
             "\\text{The path is horizontal at } t = 2",
             "A gradient of $0$ means the ball is at the highest point of its trajectory. It is still moving forward, but momentarily neither rising nor falling."),
        step(6, "Find the height at $t = 2$",
             "y = 20(2) - 5(4) = 40 - 20 = 20 \\text{ m}",
             "The maximum height is $20$ metres above the launch level."),
        step(7, "Part (c): set $\\frac{dy}{dx} = 0$",
             "20 - 10t = 0",
             "The path is horizontal when the numerator vanishes (the denominator is always $12$)."),
        step(8, "Solve for $t$",
             "t = 2",
             "The ball reaches its maximum height $2$ seconds after projection."),
        step(9, "Confirm using vertical velocity",
             "\\frac{dy}{dt} = 0 \\text{ when } t = 2",
             "Setting the vertical velocity to zero gives the same answer, which is consistent because $\\frac{dy}{dx} = 0$ requires $\\frac{dy}{dt} = 0$ when $\\frac{dx}{dt} \\neq 0$."),
        step(10, "State the position at maximum height",
              "x = 12(2) = 24 \\text{ m}",
              "The ball is $24$ metres horizontally from the launch point at its peak."),
        step(11, "Find the speed at $t = 2$",
              "v = \\sqrt{\\left(\\frac{dx}{dt}\\right)^{2} + \\left(\\frac{dy}{dt}\\right)^{2}} = \\sqrt{12^{2} + 0^{2}} = 12 \\text{ m/s}",
              "Although the path gradient is zero, the ball still has horizontal speed $12$ m/s at the peak."),
        step(12, "Compare gradient and velocity",
              "\\frac{dy}{dx} = 0 \\text{ but speed } \\neq 0",
              "The path gradient measures the slope of the trajectory, not the total speed. At the peak the ball is still moving forward."),
        step(13, "Summarise the answers",
              "\\text{(a) } \\frac{dy}{dx} = \\frac{20-10t}{12}; \\text{ (b) gradient } 0 \\text{ at peak}; \\text{ (c) } t = 2",
              "The parametric gradient tracks the path steepness and equals zero at the highest point after $2$ seconds."),
    ],
    "(a) $\\dfrac{dy}{dx} = \\dfrac{20-10t}{12}$ (path gradient); (b) $0$ at maximum height; (c) $t = 2$.",
))

# ── q067 Hard: second derivative concavity ────────────────────────────────────
questions.append(make_q(
    "q067", "Hard", 7, "exact",
    ["parametric differentiation", "second derivative", "concavity"],
    "A curve has parametric equations $x = \\cos 2t$ and $y = \\sin t$, for $0 \\leqslant t \\leqslant \\pi$. Find the value(s) of $t$ in this interval for which $\\dfrac{d^{2}y}{dx^{2}} = 0$, and state whether the curve is concave up or concave down at $t = \\dfrac{\\pi}{6}$.",
    [
        step(1, "Differentiate $x$ and $y$ with respect to $t$",
             "\\frac{dx}{dt} = -2\\sin 2t, \\qquad \\frac{dy}{dt} = \\cos t",
             "The chain rule gives $\\frac{d}{dt}(\\cos 2t) = -2\\sin 2t$."),
        step(2, "Write $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{\\cos t}{-2\\sin 2t} = \\frac{\\cos t}{-4\\sin t \\cos t} = -\\frac{1}{4\\sin t}",
             "Using $\\sin 2t = 2\\sin t \\cos t$ simplifies the expression, valid when $\\sin t \\neq 0$."),
        step(3, "Differentiate $\\frac{dy}{dx}$ with respect to $t$",
             "\\frac{d}{dt}\\!\\left(-\\frac{1}{4\\sin t}\\right) = \\frac{\\cos t}{4\\sin^{2} t}",
             "This uses $\\frac{d}{dt}(\\sin t)^{-1} = -\\cos t / \\sin^{2} t$, with the sign from the factor of $-1/4$."),
        step(4, "Write the second derivative formula",
             "\\frac{d^{2}y}{dx^{2}} = \\frac{\\dfrac{\\cos t}{4\\sin^{2} t}}{-2\\sin 2t} = \\frac{\\cos t}{-8\\sin^{2} t \\cdot 2\\sin t \\cos t} = -\\frac{1}{16\\sin^{3} t}",
             "Dividing by $\\frac{dx}{dt}$ and simplifying gives a compact expression."),
        step(5, "Set $\\frac{d^{2}y}{dx^{2}} = 0$",
             "-\\frac{1}{16\\sin^{3} t} = 0",
             "This equation has no solution because the numerator is never zero."),
        step(6, "Conclude about points of inflection",
             "\\text{No values of } t \\text{ in } [0, \\pi] \\text{ give } \\frac{d^{2}y}{dx^{2}} = 0",
             "The second derivative is never zero on the interval, so there are no inflection points in this sense."),
        step(7, "Evaluate at $t = \\dfrac{\\pi}{6}$",
             "\\sin\\!\\left(\\frac{\\pi}{6}\\right) = \\frac{1}{2}",
             "We need $\\sin(\\pi/6)$ to determine the sign of the second derivative."),
        step(8, "Compute $\\frac{d^{2}y}{dx^{2}}$ at $t = \\dfrac{\\pi}{6}$",
             "\\left.\\frac{d^{2}y}{dx^{2}}\\right|_{t=\\pi/6} = -\\frac{1}{16 \\times \\left(\\frac{1}{2}\\right)^{3}} = -\\frac{1}{2} < 0",
             "The second derivative is negative at $t = \\pi/6$."),
        step(9, "State the concavity",
             "\\text{Concave down at } t = \\frac{\\pi}{6}",
             "A negative second derivative means the curve bends downward relative to its tangent, so it is concave down."),
        step(10, "Confirm the sign of $\\frac{d^{2}y}{dx^{2}}$ on $(0, \\pi)$",
              "-\\frac{1}{16\\sin^{3} t} < 0 \\text{ for } 0 < t < \\pi",
              "Since $\\sin t > 0$ on the open interval, the second derivative is always negative, so the curve is concave down throughout."),
        step(11, "Note the domain restriction at $t = 0$ and $t = \\pi$",
              "\\sin t = 0 \\text{ at endpoints}",
              "At $t = 0$ and $t = \\pi$ the simplified formula is undefined because $\\frac{dx}{dt} = 0$, corresponding to vertical tangents."),
        step(12, "Find the coordinates at $t = \\dfrac{\\pi}{6}$",
              "x = \\cos\\!\\left(\\frac{\\pi}{3}\\right) = \\frac{1}{2}, \\qquad y = \\sin\\!\\left(\\frac{\\pi}{6}\\right) = \\frac{1}{2}",
              "The point $\\left(\\dfrac{1}{2},\\,\\dfrac{1}{2}\\right)$ lies on the curve and is concave down there."),
        step(13, "State the final answer",
              "\\text{No } t \\text{ gives } \\frac{d^{2}y}{dx^{2}} = 0; \\text{ concave down at } t = \\frac{\\pi}{6}",
              "There are no inflection points on the interval, and the curve is concave down at $t = \\pi/6$."),
    ],
    "No values of $t$ give $\\dfrac{d^{2}y}{dx^{2}} = 0$; concave down at $t = \\dfrac{\\pi}{6}$.",
))

# ── q068 Hard: perpendicular tangents (with solutions) ──────────────────────
questions.append(make_q(
    "q068", "Hard", 7, "exact",
    ["parametric differentiation", "perpendicular tangents"],
    "A curve has parametric equations $x = t^{2}$ and $y = 2t^{3} - 3t$. Find the values of $t$ for which the tangent to the curve is perpendicular to the line $x - 2y + 1 = 0$.",
    [
        step(1, "Find the gradient of the given line",
             "x - 2y + 1 = 0 \\Rightarrow y = \\frac{x}{2} + \\frac{1}{2}, \\quad m = \\frac{1}{2}",
             "Rearranging to slope-intercept form reveals gradient $\\frac{1}{2}$."),
        step(2, "State the perpendicular gradient",
             "m_{\\text{tangent}} = -2",
             "The negative reciprocal of $\\frac{1}{2}$ is $-2$."),
        step(3, "Differentiate the parametric equations",
             "\\frac{dx}{dt} = 2t, \\qquad \\frac{dy}{dt} = 6t^{2} - 3",
             "Both first derivatives are required for the parametric gradient."),
        step(4, "Set $\\frac{dy}{dx} = -2$",
             "\\frac{6t^{2} - 3}{2t} = -2",
             "We solve for $t$ where the tangent gradient equals $-2$."),
        step(5, "Clear the fraction",
             "6t^{2} - 3 = -4t",
             "Multiplying by $2t$ is valid for $t \\neq 0$."),
        step(6, "Rearrange into quadratic form",
             "6t^{2} + 4t - 3 = 0",
             "All terms are on one side."),
        step(7, "Apply the quadratic formula",
             "t = \\frac{-4 \\pm \\sqrt{16 + 72}}{12} = \\frac{-4 \\pm \\sqrt{88}}{12} = \\frac{-4 \\pm 2\\sqrt{22}}{12} = \\frac{-2 \\pm \\sqrt{22}}{6}",
             "The discriminant is $16 + 72 = 88 = 4 \\times 22$."),
        step(8, "Check $t = 0$ separately",
             "\\left.\\frac{dy}{dx}\\right|_{t=0} \\text{ is undefined}",
             "At $t = 0$ the tangent is vertical, which cannot have gradient $-2$."),
        step(9, "Simplify the discriminant",
             "\\sqrt{88} = \\sqrt{4 \\times 22} = 2\\sqrt{22}",
             "Factorising the surd under the square root makes the final answer neater."),
        step(10, "Verify the first solution",
              "t = \\frac{-2 + \\sqrt{22}}{6}: \\quad \\frac{6t^{2}-3}{2t} = -2",
              "Substituting $t = \\dfrac{-2+\\sqrt{22}}{6}$ back into the gradient formula confirms the tangent gradient is $-2$."),
        step(11, "Verify the second solution",
              "t = \\frac{-2 - \\sqrt{22}}{6}: \\quad \\frac{dy}{dx} = -2",
              "Both roots of the quadratic satisfy the perpendicularity condition."),
        step(12, "Find the coordinates at each value of $t$",
              "x = t^{2}, \\qquad y = 2t^{3} - 3t",
              "Each valid $t$ gives a distinct point on the curve where the tangent is perpendicular to the given line."),
        step(13, "State the exact values",
              "t = \\dfrac{-2 + \\sqrt{22}}{6} \\quad \\text{and} \\quad t = \\dfrac{-2 - \\sqrt{22}}{6}",
              "These are the two parameter values where the tangent is perpendicular to the given line."),
    ],
    "$t = \\dfrac{-2 + \\sqrt{22}}{6}$ and $t = \\dfrac{-2 - \\sqrt{22}}{6}$.",
))

# ── q069 Hard: comprehensive multi-part ───────────────────────────────────────
questions.append(make_q(
    "q069", "Hard", 10, "exact",
    ["parametric differentiation", "stationary points", "tangent", "normal", "multi-part"],
    "A curve $C$ has parametric equations $x = t^{3} - 6t$ and $y = t^{2} - 2$.\n\n**(a)** Find $\\dfrac{dy}{dx}$ in terms of $t$.\n\n**(b)** Find the coordinates of each stationary point on $C$.\n\n**(c)** Determine the nature of each stationary point.\n\n**(d)** Find the equation of the normal to $C$ at the stationary point.",
    [
        step(1, "Differentiate with respect to $t$",
             "\\frac{dx}{dt} = 3t^{2} - 6 = 3(t^{2} - 2), \\qquad \\frac{dy}{dt} = 2t",
             "These first derivatives underpin all four parts."),
        step(2, "Part (a): write $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{2t}{3(t^{2} - 2)}",
             "The gradient is defined wherever $t^{2} \\neq 2$."),
        step(3, "Part (b): set $\\frac{dy}{dx} = 0$",
             "2t = 0 \\Rightarrow t = 0",
             "The numerator must be zero. At $t = 0$, $\\frac{dx}{dt} = -6 \\neq 0$, so this is a valid stationary point."),
        step(4, "Find coordinates at $t = 0$",
             "x = 0, \\qquad y = -2",
             "The only stationary point is $(0,\\,-2)$."),
        step(5, "Check for other stationary points",
             "t^{2} = 2 \\Rightarrow \\frac{dx}{dt} = 0",
             "At $t = \\pm\\sqrt{2}$, the tangent is vertical, not horizontal, so these are not stationary points."),
        step(6, "Part (c): differentiate $\\frac{dy}{dx}$ for the second derivative",
             "\\frac{d}{dt}\\!\\left(\\frac{2t}{3(t^{2}-2)}\\right) = \\frac{2 \\cdot 3(t^{2}-2) - 2t \\cdot 6t}{9(t^{2}-2)^{2}} = \\frac{6(t^{2}-2) - 12t^{2}}{9(t^{2}-2)^{2}} = \\frac{-6t^{2} - 12}{9(t^{2}-2)^{2}}",
             "The quotient rule gives a simplified numerator $-6(t^{2}+2)$."),
        step(7, "Evaluate $\\frac{d^{2}y}{dx^{2}}$ at $t = 0$",
             "\\left.\\frac{d}{dt}\\!\\left(\\frac{dy}{dx}\\right)\\right|_{t=0} = \\frac{-12}{9 \\times 4} = -\\frac{1}{3}",
             "At $t = 0$ the numerator of the second derivative is $-12$."),
        step(8, "Complete the second derivative at $t = 0$",
             "\\left.\\frac{d^{2}y}{dx^{2}}\\right|_{t=0} = \\frac{-1/3}{-6} = \\frac{1}{18} > 0",
             "A positive second derivative confirms a local minimum."),
        step(9, "State the nature",
             "\\text{Minimum at } (0,\\,-2)",
             "There is only one stationary point and it is a minimum."),
        step(10, "Part (d): find the tangent gradient at the stationary point",
              "\\left.\\frac{dy}{dx}\\right|_{t=0} = 0",
              "At the stationary point the tangent is horizontal, so its gradient is zero."),
        step(11, "Find the normal gradient",
              "m_{\\text{normal}} \\text{ is undefined (vertical normal)}",
              "A line perpendicular to a horizontal tangent is vertical."),
        step(12, "Write the normal equation",
              "x = 0",
              "The vertical line through $(0,\\,-2)$ is the normal at the stationary point."),
        step(13, "State all four answers",
              "\\text{(a) } \\frac{dy}{dx} = \\frac{2t}{3(t^{2}-2)}; \\text{ (b) } (0,-2); \\text{ (c) minimum; (d) } x = 0",
              "The curve has a single minimum at $(0,\\,-2)$ with vertical normal $x = 0$."),
    ],
    "(a) $\\dfrac{dy}{dx} = \\dfrac{2t}{3(t^{2}-2)}$; (b) $(0,\\,-2)$; (c) minimum; (d) normal $x = 0$.",
))

# ── q070 Hard: comprehensive exam question ────────────────────────────────────
questions.append(make_q(
    "q070", "Hard", 10, "exact",
    ["parametric differentiation", "tangent", "normal", "area", "multi-part", "exam"],
    "A curve $C$ has parametric equations $x = t^{2}$ and $y = t^{3} - 3t$.\n\n**(a)** Show that $\\dfrac{dy}{dx} = \\dfrac{3(t^{2} - 1)}{2t}$ for $t \\neq 0$.\n\n**(b)** The tangent to $C$ at the point where $t = 2$ meets the coordinate axes at $A$ and $B$. Find the area of triangle $OAB$, where $O$ is the origin.\n\n**(c)** Find the values of $t$ for which the tangent to $C$ is parallel to the line $y = 6x$.\n\n**(d)** The normal to $C$ at the point where $t = 1$ meets the curve again at $Q$. Given that $Q$ corresponds to $t = -1$, verify that $Q$ lies on the normal.",
    [
        step(1, "Differentiate the parametric equations",
             "\\frac{dx}{dt} = 2t, \\qquad \\frac{dy}{dt} = 3t^{2} - 3",
             "These first derivatives are used in every part of the question."),
        step(2, "Part (a): form $\\frac{dy}{dx}$",
             "\\frac{dy}{dx} = \\frac{3t^{2} - 3}{2t} = \\frac{3(t^{2} - 1)}{2t}",
             "Factorising the numerator confirms the required result for $t \\neq 0$."),
        step(3, "Part (b): find the point at $t = 2$",
             "x = 4, \\qquad y = 8 - 6 = 2",
             "The point is $P(4,\\,2)$."),
        step(4, "Find the tangent gradient at $t = 2$",
             "\\left.\\frac{dy}{dx}\\right|_{t=2} = \\frac{3(4-1)}{4} = \\frac{9}{4}",
             "The tangent has gradient $\\frac{9}{4}$."),
        step(5, "Write the tangent equation",
             "y - 2 = \\frac{9}{4}(x - 4)",
             "Point-gradient form through $(4,\\,2)$."),
        step(6, "Find the axis intercepts",
             "x\\text{-axis: } y = 0 \\Rightarrow x = 4 - \\frac{8}{9} = \\frac{28}{9}; \\qquad y\\text{-axis: } y = 2 - 9 = -7",
             "The intercepts are $A\\!\\left(\\dfrac{28}{9},\\,0\\right)$ and $B(0,\\,-7)$."),
        step(7, "Calculate the area of triangle $OAB$",
             "\\text{Area} = \\frac{1}{2} \\times \\frac{28}{9} \\times 7 = \\frac{98}{9}",
             "Half the product of the intercept lengths gives the area."),
        step(8, "Part (c): set gradient equal to $6$",
             "\\frac{3(t^{2} - 1)}{2t} = 6",
             "Parallel tangents share the gradient of $y = 6x$."),
        step(9, "Solve the equation",
             "3t^{2} - 3 = 12t \\Rightarrow 3t^{2} - 12t - 3 = 0 \\Rightarrow t^{2} - 4t - 1 = 0",
             "Dividing by $3$ and rearranging gives a standard quadratic."),
        step(10, "Apply the quadratic formula",
              "t = \\frac{4 \\pm \\sqrt{16 + 4}}{2} = \\frac{4 \\pm \\sqrt{20}}{2} = 2 \\pm \\sqrt{5}",
              "Two distinct real values of $t$ give tangents parallel to $y = 6x$."),
        step(11, "Part (d): find the point at $t = 1$",
              "x = 1, \\qquad y = 1 - 3 = -2",
              "The point is $P(1,\\,-2)$."),
        step(12, "Find the normal gradient at $t = 1$",
              "\\left.\\frac{dy}{dx}\\right|_{t=1} = 0 \\Rightarrow m_{\\text{normal}} \\text{ is undefined (vertical normal)}",
              "At $t = 1$, $\\frac{dy}{dx} = 0$, so the tangent is horizontal and the normal is vertical."),
        step(13, "Write the normal equation",
              "x = 1",
              "The vertical line through $(1,\\,-2)$ is the normal."),
        step(14, "Find coordinates of $Q$ at $t = -1$",
              "x = (-1)^{2} = 1, \\qquad y = (-1)^{3} - 3(-1) = -1 + 3 = 2",
              "The second intersection is $Q(1,\\,2)$."),
        step(15, "Verify $Q$ lies on the normal $x = 1$",
              "x = 1 \\text{ at } Q",
              "Since $Q$ has $x$-coordinate $1$, it lies on the vertical normal line $x = 1$, confirming the normal meets the curve again at $Q$."),
        step(16, "Explain the geometric situation",
              "t = 1 \\text{ and } t = -1 \\text{ give points } (1,-2) \\text{ and } (1,2)",
              "Both points have $x = 1$, so they lie on a vertical line. The normal at $t = 1$ is this same vertical line, which intersects the curve again at $t = -1$."),
        step(17, "State the final answers",
              "\\text{(a) shown; (b) area } \\frac{98}{9}; \\text{ (c) } t = 2 \\pm \\sqrt{5}; \\text{ (d) verified}",
              "All four parts are complete: the gradient formula, triangle area $\\frac{98}{9}$, parallel tangent values $t = 2 \\pm \\sqrt{5}$, and verification that $Q(1,\\,2)$ lies on the normal."),
    ],
    "(a) Shown; (b) area $= \\dfrac{98}{9}$; (c) $t = 2 \\pm \\sqrt{5}$; (d) $Q(1,\\,2)$ lies on the normal $x = 1$.",
))

assert len(questions) == 17, f"Expected 17 questions, got {len(questions)}"

# Validate step counts
for q in questions:
    n = len(q["workedSolution"]["steps"])
    diff = q["difficulty"]
    if diff == "Intermediate" and not (9 <= n <= 13):
        print(f"WARN {q['id']}: Intermediate has {n} steps")
    if diff == "Hard" and not (13 <= n <= 18):
        print(f"WARN {q['id']}: Hard has {n} steps")

write_questions_ts(
    OUT,
    questions,
    batch_label="Parametric differentiation q054–q070",
)
print(f"Wrote {len(questions)} questions to {OUT}")
